const Map<String, Map<String, dynamic>> chartTemplates = {
  '/api/v1/charts/build': {
    'kind': 'natal',
    'tz': 'Europe/Istanbul',
    'a': {
      'name': 'partner_a',
      'data': {
        'birthDate': '1990-01-01',
        'birthTime': '12:00',
        'birthPlace': 'Istanbul',
      },
    },
  },
  '/api/v1/relationship/synastry/analyze': {
    'partner_a': {
      'birthDate': '1990-01-01',
      'birthTime': '12:00',
      'birthPlace': 'Istanbul',
    },
    'partner_b': {
      'birthDate': '1992-06-15',
      'birthTime': '08:30',
      'birthPlace': 'Istanbul',
    },
    'options': {'include_debug': true},
  },
  '/api/synastry/analyze': {
    'partner_a': {
      'birthDate': '1990-01-01',
      'birthTime': '12:00',
      'birthPlace': 'Istanbul',
    },
    'partner_b': {
      'birthDate': '1992-06-15',
      'birthTime': '08:30',
      'birthPlace': 'Istanbul',
    },
  },
  '/interpret': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'locale': 'tr',
  },
  '/interpret/ui': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'locale': 'tr',
  },
  '/interpret/debug': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'locale': 'tr',
  },
  '/interpret/premium': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'locale': 'tr',
  },
  '/interpret/premium/ui': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'locale': 'tr',
  },
  '/interpret/premium/debug': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'locale': 'tr',
  },
  '/transits': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'transit_date': '2026-02-21',
    'transit_place': 'Istanbul',
    'tz': 'Europe/Istanbul',
  },
  '/transits/debug': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'start': '2026-02-01',
    'end': '2026-02-15',
    'tz': 'Europe/Istanbul',
  },
  '/transits/window': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'start': '2026-02-01',
    'end': '2026-02-15',
    'tz': 'Europe/Istanbul',
  },
  '/transits/event_timing': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'intent': 'beauty_care',
    'start': '2026-02-01',
    'end': '2026-02-15',
    'tz': 'Europe/Istanbul',
  },
  '/transit/calendar/day': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'date': '2026-02-21',
    'tz': 'Europe/Istanbul',
    'view': 'public',
  },
  '/transit/calendar': {
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'start': '2026-02-01',
    'end': '2026-02-28',
    'tz': 'Europe/Istanbul',
    'view': 'public',
  },
  '/transit/calendar/best-times': {
    'intent': 'beauty_care_nourish',
    'birth_date': '1990-01-01',
    'birth_time': '12:00',
    'birth_place': 'Istanbul',
    'start': '2026-02-01',
    'end': '2026-02-28',
    'tz': 'Europe/Istanbul',
  },
};
