from __future__ import annotations

from typing import Any, Dict, List


PERSONALITY_IMPRINT_LIBRARY_TR_V3: Dict[str, List[Dict[str, Any]]] = {
    "moon_signs": [
        {
            "key": "moon_aries",
            "kind": "sign_placement",
            "label_tr": "Ay Koç",
            "tags": ["dürüst duygu", "hızlı tepki", "ateşli kalp"],
            "aura": "Duyguların beklemeyi pek sevmez; içinde olan şey yüzüne ve enerjine hızlıca çıkabilir.",
            "trait": "Sen hislerinde direkt, canlı ve anlık tepki vermeye yatkınsın.",
            "drive": "İçinde kendi duyguna sadık kalma ve gecikmeden hareket etme ihtiyacı vardır.",
            "shadow": "Bazen sabırsız, fevri ya da çabuk yükselen tepkiler verebilirsin.",
        },
        {
            "key": "moon_taurus",
            "kind": "sign_placement",
            "label_tr": "Ay Boğa",
            "tags": ["sakin", "duyusal", "güven arayan"],
            "aura": "Sende huzur veren, sabit ve yumuşak bir duygusal ton olabilir.",
            "trait": "Sen hislerini kolay savurmaz; güven ve istikrar içinde açarsın.",
            "drive": "İçinde sakinlik, sadelik ve dokunabildiğin bir güven kurma ihtiyacı güçlüdür.",
            "shadow": "Bazen değişime direnebilir ya da duygusal konfor alanına fazla tutunabilirsin.",
        },
        {
            "key": "moon_gemini",
            "kind": "sign_placement",
            "label_tr": "Ay İkizler",
            "tags": ["hareketli duygu", "merak", "zihinsel kalp"],
            "aura": "Duyguların ağır ağır değil; düşünceyle, merakla ve hareketle akma eğilimindedir.",
            "trait": "Sen hislerini anlamak için çoğu zaman konuşmaya, sormaya ve bağlantı kurmaya ihtiyaç duyarsın.",
            "drive": "İçinde zihinsel canlılık, paylaşım ve duyguyu kelimeye dökme ihtiyacı vardır.",
            "shadow": "Bazen fazla dağılabilir ya da derin hissi hızlıca zihinselleştirebilirsin.",
        },
        {
            "key": "moon_cancer",
            "kind": "sign_placement",
            "label_tr": "Ay Yengeç",
            "tags": ["şefkat", "koruma", "yüksek hassasiyet"],
            "aura": "Kalbin dış dünyayı güçlü hisseder; ortamın sıcaklığı ya da sertliği sana kolay geçebilir.",
            "trait": "Sen duygusal olarak korumacı, sezgisel ve bağ odaklı birisin.",
            "drive": "İçinde ait olmak, güvenli bağlar kurmak ve sevdiklerini kollamak isteyen güçlü bir taraf vardır.",
            "shadow": "Bazen fazla alıngan olabilir ya da içeri çekilerek kendini korumaya çalışabilirsin.",
        },
        {
            "key": "moon_leo",
            "kind": "sign_placement",
            "label_tr": "Ay Aslan",
            "tags": ["sıcak", "görünür duygu", "gururlu kalp"],
            "aura": "Kalbin loşta yaşamıyor; bağlandığında sıcaklığın fark edilir hale geliyor.",
            "trait": "Sen duygularını büyük, canlı ve içten bir yerden yaşarsın.",
            "drive": "İçinde sevilmek, görülmek ve kalpten verdiğin şeyin karşılık bulduğunu hissetmek isteyen güçlü bir ihtiyaç vardır.",
            "shadow": "Bazen gurur yarası, onay ihtiyacı ya da dramatik tepkiler öne çıkabilir.",
        },
        {
            "key": "moon_virgo",
            "kind": "sign_placement",
            "label_tr": "Ay Başak",
            "tags": ["dikkatli", "ince ayar", "faydalı sevgi"],
            "aura": "Duygun büyük gösterilerle değil; özen, dikkat ve küçük ayrıntılarla görünür olur.",
            "trait": "Sen hislerini düzenleyerek, toparlayarak ve işe yarar hale getirerek yaşama eğilimindesin.",
            "drive": "İçinde faydalı olmak, dağınık olanı düzenlemek ve sevdiklerine somut destek vermek ihtiyacı vardır.",
            "shadow": "Bazen fazla analiz edebilir ya da duygunu rahat bırakmak yerine düzeltmeye çalışabilirsin.",
        },
        {
            "key": "moon_libra",
            "kind": "sign_placement",
            "label_tr": "Ay Terazi",
            "tags": ["uyum", "nazik duygu", "ilişki hassasiyeti"],
            "aura": "Kalbin sertlikten çok uyuma, güzelliğe ve karşılıklı dengeye açılır.",
            "trait": "Sen duygusal olarak nazik, ilişki odaklı ve uyum arayan bir yapıya sahipsin.",
            "drive": "İçinde huzur, karşılıklı anlayış ve duygusal zarafet kurma isteği güçlüdür.",
            "shadow": "Bazen gerçek his yerine huzuru korumaya çalışabilir ya da kararsızlığa kayabilirsin.",
        },
        {
            "key": "moon_scorpio",
            "kind": "sign_placement",
            "label_tr": "Ay Akrep",
            "tags": ["yoğun", "gizli derinlik", "sezgisel güç"],
            "aura": "Duyguların yüzeyde durmaz; sende hissin alt katmanları daha güçlü çalışır.",
            "trait": "Sen güvenmeden açılmayan ama bağ kurunca çok derin hisseden birisin.",
            "drive": "İçinde gerçek güven, duygusal sadakat ve yüzeyin altına inen bağlar kurma ihtiyacı vardır.",
            "shadow": "Bazen şüphe, kıskançlık ya da duygusal kontrol ihtiyacı ağır basabilir.",
        },
        {
            "key": "moon_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Ay Yay",
            "tags": ["neşe", "özgür ruh", "açık duygu"],
            "aura": "Duygunu boğan şey dar alanlar olur; kalbin genişledikçe canlanır.",
            "trait": "Sen hislerinde açık, samimi ve ileriye bakan bir akış taşırsın.",
            "drive": "İçinde özgür hissetmek, anlam bulmak ve hayatın sana alan açtığını hissetmek ihtiyacı vardır.",
            "shadow": "Bazen derin duyguyu hafifleterek geçebilir ya da fazla kaçışa yönelebilirsin.",
        },
        {
            "key": "moon_capricorn",
            "kind": "sign_placement",
            "label_tr": "Ay Oğlak",
            "tags": ["kontrollü duygu", "dayanıklılık", "iç disiplin"],
            "aura": "Kalbin çok şey hisseder ama bunu herkese açık yaşamaz; sende önce kontrol gelir.",
            "trait": "Sen duygularını ciddiye alan, kolay bırakmayan ve erken olgunlaşmış bir enerji taşıyorsun.",
            "drive": "İçinde güçlü kalmak, dağılmamak ve duygusal olarak kendi ayakların üzerinde durmak isteyen bir taraf vardır.",
            "shadow": "Bazen fazla kendini tutabilir ya da yardım isterken bile mesafeli kalabilirsin.",
        },
        {
            "key": "moon_aquarius",
            "kind": "sign_placement",
            "label_tr": "Ay Kova",
            "tags": ["özgün duygu", "mesafe", "zihinsel özgürlük"],
            "aura": "Kalbin alışılmış şekilde bağlanmak istemeyebilir; duyguda bile sana alan gerekir.",
            "trait": "Sen hislerinde özgün, bağımsız ve bazen çözülmesi zor bir ritim taşırsın.",
            "drive": "İçinde kendi duygusal alanını koruma ve yakınlık içinde bile kendin kalma ihtiyacı vardır.",
            "shadow": "Bazen duygusal mesafe artabilir ya da kırılganlığını akıl üzerinden saklayabilirsin.",
        },
        {
            "key": "moon_pisces",
            "kind": "sign_placement",
            "label_tr": "Ay Balık",
            "tags": ["yüksek sezgi", "şefkat", "akışkan duygu"],
            "aura": "Kalbin sınırları ince hissedebilir; ortam, insan ve enerji sana kolay dokunur.",
            "trait": "Sen duygusal olarak sezgisel, merhametli ve derinden etkilenebilen birisin.",
            "drive": "İçinde ruhsal bağ, şefkat ve hayatla daha ince bir yerden temas kurma isteği vardır.",
            "shadow": "Bazen fazla etkilenebilir, dağılıp kaybolabilir ya da kaçış eğilimine girebilirsin.",
        },
    ],
    "mercury_signs": [
        {
            "key": "mercury_aries",
            "kind": "sign_placement",
            "label_tr": "Merkür Koç",
            "tags": ["hızlı zihin", "direkt söz", "ateşli ifade"],
            "aura": "Zihnin bekleyerek değil, ateş alarak çalışabilir; net gördüğünde cümlen de hızla gelir.",
            "trait": "Sen düşünceni dolandırmadan, kısa ve direkt ifade etmeye yatkınsın.",
            "drive": "İçinde konuyu hızla kavrama ve düşünceyi eyleme yakın tutma isteği vardır.",
            "shadow": "Bazen fazla keskin, sabırsız ya da düşünmeden söyleyen bir tarafa kayabilirsin.",
        },
        {
            "key": "mercury_taurus",
            "kind": "sign_placement",
            "label_tr": "Merkür Boğa",
            "tags": ["sağlam zihin", "ölçülü söz", "sakin düşünce"],
            "aura": "Zihnin aceleyle değil, yerleşerek çalışır; cümlen yavaş kurulur ama boş gitmez.",
            "trait": "Sen düşünürken sağlamlık, somutluk ve netlik ararsın.",
            "drive": "İçinde fikri oturtmak, sabitlemek ve gerçek hayatta karşılığı olan şeyler söylemek ihtiyacı vardır.",
            "shadow": "Bazen inatlaşabilir ya da yeni fikirlere gereğinden yavaş açılabilirsin.",
        },
        {
            "key": "mercury_gemini",
            "kind": "sign_placement",
            "label_tr": "Merkür İkizler",
            "tags": ["kıvrak", "meraklı", "çok yönlü ifade"],
            "aura": "Zihnin bağlantı kurmayı sever; bir şeyden başka bir şeye hızla sıçrayabilirsin.",
            "trait": "Sen konuşarak, sorarak, kıyaslayarak ve çok yönlü düşünerek ilerlersin.",
            "drive": "İçinde öğrenme, anlatma ve zihinsel hareketi canlı tutma ihtiyacı çok güçlüdür.",
            "shadow": "Bazen dağılabilir, fazla konuşabilir ya da derinlik yerine hızda kalabilirsin.",
        },
        {
            "key": "mercury_cancer",
            "kind": "sign_placement",
            "label_tr": "Merkür Yengeç",
            "tags": ["sezgisel zihin", "duygulu ifade", "hatırlayan akıl"],
            "aura": "Sözün sadece bilgi taşımaz; his de taşır, hafıza da taşır.",
            "trait": "Sen düşünürken duygusal tonu, geçmişi ve insan etkisini hesaba katarsın.",
            "drive": "İçinde anlamlı konuşmak, güvenli bağ kurmak ve kelimelerle koruyucu bir alan açmak isteği vardır.",
            "shadow": "Bazen fazla kişiselleştirebilir ya da konuya duygusal ağırlık bindirebilirsin.",
        },
        {
            "key": "mercury_leo",
            "kind": "sign_placement",
            "label_tr": "Merkür Aslan",
            "tags": ["güçlü ifade", "karizmatik söz", "görünür akıl"],
            "aura": "Söz sende aksesuar gibi durmuyor; karakterin doğrudan cümlene karışıyor.",
            "trait": "Sen konuşurken görünür olursun; ifaden canlı, belirgin ve dikkat çekici olabilir.",
            "drive": "İçinde net duyulmak, etki bırakmak ve fikrini güçlü biçimde ortaya koymak isteği vardır.",
            "shadow": "Bazen fazla iddialı konuşabilir ya da eleştiri karşısında gurur savunması yapabilirsin.",
        },
        {
            "key": "mercury_virgo",
            "kind": "sign_placement",
            "label_tr": "Merkür Başak",
            "tags": ["analitik", "ayıklayan zihin", "detay hassasiyeti"],
            "aura": "Zihnin dağınık olanı toplamaya, pürüzü görmeye ve sistemi düzeltmeye yatkındır.",
            "trait": "Sen ayrıntı, doğruluk ve işlev üzerinden düşünen birisin.",
            "drive": "İçinde netleştirmek, ayıklamak ve zihinsel olarak temiz bir düzen kurmak ihtiyacı vardır.",
            "shadow": "Bazen fazla eleştirel olabilir ya da küçük hatalara gereğinden çok takılabilirsin.",
        },
        {
            "key": "mercury_libra",
            "kind": "sign_placement",
            "label_tr": "Merkür Terazi",
            "tags": ["diplomatik", "ölçülü söz", "denge arayan akıl"],
            "aura": "Sözün çoğu zaman köprü kurar; zihnin karşı tarafı da hesaba katar.",
            "trait": "Sen düşünürken ilişkiyi, uyumu ve iki taraflı resmi görmeye çalışırsın.",
            "drive": "İçinde dengeli konuşmak, adil olmak ve kelimelerle sertliği yumuşatmak isteği vardır.",
            "shadow": "Bazen kesinleşmekte zorlanabilir ya da huzur uğruna düşünceni fazla yumuşatabilirsin.",
        },
        {
            "key": "mercury_scorpio",
            "kind": "sign_placement",
            "label_tr": "Merkür Akrep",
            "tags": ["derin zihin", "keskin sezgi", "gizli analiz"],
            "aura": "Zihnin yüzeyde durmaz; çoğu zaman söylenmeyeni de okumaya çalışır.",
            "trait": "Sen düşünürken derine iner, niyeti sezmek ve alt katmanı görmek istersin.",
            "drive": "İçinde hakikati bulmak, perdeyi kaldırmak ve gerçekten ne olduğunu anlamak ihtiyacı vardır.",
            "shadow": "Bazen fazla kuşkucu olabilir ya da zihinsel olarak takıntıya kayabilirsin.",
        },
        {
            "key": "mercury_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Merkür Yay",
            "tags": ["büyük resim", "açık söz", "vizyoner düşünce"],
            "aura": "Zihnin ayrıntıdan çok anlamı ve yönü görmek ister; cümlen geniş alan açabilir.",
            "trait": "Sen düşünürken büyüğe, uzağa ve fikrin taşıdığı anlama bakarsın.",
            "drive": "İçinde özgür düşünmek, açık konuşmak ve bir şeyin niçinini bulmak isteği vardır.",
            "shadow": "Bazen detay kaçırabilir ya da doğruculuk adına fazlaca sertleşebilirsin.",
        },
        {
            "key": "mercury_capricorn",
            "kind": "sign_placement",
            "label_tr": "Merkür Oğlak",
            "tags": ["stratejik zihin", "ciddi ifade", "yapı kuran akıl"],
            "aura": "Zihnin boşlukta kalmayı sevmiyor; düşünceni zemine bastırmak istiyorsun.",
            "trait": "Sen planlı, ölçülü ve sonuç odaklı düşünen birisin.",
            "drive": "İçinde işe yarayan, sağlam ve sürdürülebilir düşünce üretme ihtiyacı vardır.",
            "shadow": "Bazen fazla katı olabilir ya da spontane fikir akışını erken kesebilirsin.",
        },
        {
            "key": "mercury_aquarius",
            "kind": "sign_placement",
            "label_tr": "Merkür Kova",
            "tags": ["orijinal", "bağımsız akıl", "farklı bakış"],
            "aura": "Zihnin hazır yolları izlemekten çok kendi bağlantılarını kurmayı sever.",
            "trait": "Sen sıradan düşünmek yerine farklı açıdan bakan, özgün ve bağımsız bir akıl taşırsın.",
            "drive": "İçinde yeni bir bakış bulmak, kalıbı sorgulamak ve zihinsel özgürlüğü korumak isteği vardır.",
            "shadow": "Bazen kopuk görünebilir ya da karşı tarafı duygusal olarak geride bırakacak kadar zihinselleşebilirsin.",
        },
        {
            "key": "mercury_pisces",
            "kind": "sign_placement",
            "label_tr": "Merkür Balık",
            "tags": ["imge", "sezgi", "şiirsel zihin"],
            "aura": "Düşüncen düz çizgiyle değil; çağrışım, his ve imgeyle akabilir.",
            "trait": "Sen bazen kelimeden çok hissi, mantıktan çok sezgiyi takip eden bir zihin taşırsın.",
            "drive": "İçinde görünmeyeni hissetmek, anlamı ince katmanlarda bulmak ve hayal gücüyle düşünmek isteği vardır.",
            "shadow": "Bazen zihinsel sis, karışıklık ya da net anlatımda zorlanma yaşayabilirsin.",
        },
    ],
    "venus_signs": [
        {
            "key": "venus_aries",
            "kind": "sign_placement",
            "label_tr": "Venüs Koç",
            "tags": ["direkt çekim", "canlı sevgi", "ilk adım"],
            "aura": "Kalbin bekleyerek değil, kıvılcım alarak açılabilir; çekim sende hızlı başlar.",
            "trait": "Sen sevgide canlılık, cesaret ve doğrudanlık taşırsın.",
            "drive": "İçinde heyecan duymak, ilk kıvılcımı hissetmek ve sevgiye cesur yaklaşmak isteği vardır.",
            "shadow": "Bazen sabırsız bağlanabilir ya da heyecan düştüğünde çabuk uzaklaşabilirsin.",
        },
        {
            "key": "venus_taurus",
            "kind": "sign_placement",
            "label_tr": "Venüs Boğa",
            "tags": ["duyusal sevgi", "sadakat", "konfor"],
            "aura": "Sevgin acele etmiyor; sende çekim güven, istikrar ve bedensel huzurla açılıyor.",
            "trait": "Sen sevgiyi sakin, sadık ve somut bir yerden yaşarsın.",
            "drive": "İçinde huzurlu bağ, kalıcı temas ve güzel bir yaşam duygusu kurma isteği vardır.",
            "shadow": "Bazen sahiplenebilir ya da alıştığın ilişkisel zemini bırakmakta zorlanabilirsin.",
        },
        {
            "key": "venus_gemini",
            "kind": "sign_placement",
            "label_tr": "Venüs İkizler",
            "tags": ["oyunlu sevgi", "zihinsel çekim", "hareket"],
            "aura": "Kalbin önce zihinden kıvılcım alabilir; konuşma sende çekimin önemli bir parçasıdır.",
            "trait": "Sen sevgide merak, neşe ve zihinsel akış ararsın.",
            "drive": "İçinde paylaşmak, gülmek, konuşmak ve ilişkinin canlı kalmasını istemek vardır.",
            "shadow": "Bazen derinleşmekten çok akışta kalabilir ya da çabuk sıkılabilirsin.",
        },
        {
            "key": "venus_cancer",
            "kind": "sign_placement",
            "label_tr": "Venüs Yengeç",
            "tags": ["şefkatli sevgi", "koruma", "duygusal bağ"],
            "aura": "Sevgin gösterişten çok sıcaklık ve güvenli yakınlık üzerinden hissedilir.",
            "trait": "Sen ilişkide koruyan, bağ kuran ve duygusal hafızası güçlü birisin.",
            "drive": "İçinde ait hissetmek, sevgiyle yuva duygusu kurmak ve duygusal bağlılık yaşamak isteği vardır.",
            "shadow": "Bazen fazla hassas olabilir ya da sevgide güvence ararken içine kapanabilirsin.",
        },
        {
            "key": "venus_leo",
            "kind": "sign_placement",
            "label_tr": "Venüs Aslan",
            "tags": ["parlak sevgi", "cömert kalp", "görünür çekim"],
            "aura": "Sevgin saklanmayı sevmez; sende kalp biraz altın ışıkla çalışabilir.",
            "trait": "Sen ilişkide sıcak, cömert ve görünür bir sevme biçimi taşırsın.",
            "drive": "İçinde özel hissetmek, sevmekle parlamak ve sevildiğini net görmek isteği vardır.",
            "shadow": "Bazen ilgi açlığı, gurur yarası ya da dramaya açıklık artabilir.",
        },
        {
            "key": "venus_virgo",
            "kind": "sign_placement",
            "label_tr": "Venüs Başak",
            "tags": ["ince sevgi", "özen", "seçicilik"],
            "aura": "Kalbin büyük sözlerle değil; dikkat, detay ve özenle kendini gösterir.",
            "trait": "Sen sevgiyi hizmet, emek ve küçük ama anlamlı dokunuşlarla yaşarsın.",
            "drive": "İçinde faydalı olmak, gerçekten iyi gelmek ve ilişkide temiz bir düzen kurmak isteği vardır.",
            "shadow": "Bazen fazla seçici olabilir ya da sevgiyi rahat bırakmak yerine düzeltmeye çalışabilirsin.",
        },
        {
            "key": "venus_libra",
            "kind": "sign_placement",
            "label_tr": "Venüs Terazi",
            "tags": ["zarafet", "uyum", "ilişki estetiği"],
            "aura": "Sende ilişki kurmayı kolaylaştıran doğal bir yumuşaklık ve zarafet olabilir.",
            "trait": "Sen sevgide uyum, karşılıklılık ve estetik denge ararsın.",
            "drive": "İçinde güzel bir bağ kurmak, nazik bir alışveriş yaşamak ve ilişki içinde incelik hissetmek isteği vardır.",
            "shadow": "Bazen huzur uğruna fazla taviz verebilir ya da kararsız kalabilirsin.",
        },
        {
            "key": "venus_scorpio",
            "kind": "sign_placement",
            "label_tr": "Venüs Akrep",
            "tags": ["yoğun çekim", "derin bağ", "manyetik sevgi"],
            "aura": "Sevgin hafif akmıyor; biri sana değdiğinde mesele yüzeyde kalmayabiliyor.",
            "trait": "Sen ilişkide derinlik, sadakat ve duygusal çıplaklık arayan birisin.",
            "drive": "İçinde gerçek birleşme, güçlü bağ ve yüzeyin altındaki sevgiyi yaşama isteği vardır.",
            "shadow": "Bazen kıskançlık, güç savaşı ya da fazla yoğun bağlanma görülebilir.",
        },
        {
            "key": "venus_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Venüs Yay",
            "tags": ["özgür sevgi", "neşe", "açık kalp"],
            "aura": "Kalbin dar odada yaşamıyor; sevgi sende alan, neşe ve dürüstlük isteyebilir.",
            "trait": "Sen sevgide özgürlük, içtenlik ve birlikte genişleme duygusu ararsın.",
            "drive": "İçinde ilham duymak, hayatı paylaşırken çoğalmak ve sevginin canlı kalmasını istemek vardır.",
            "shadow": "Bazen bağ derinleşmeden alan istemeye kaçabilir ya da fazla rahat davranabilirsin.",
        },
        {
            "key": "venus_capricorn",
            "kind": "sign_placement",
            "label_tr": "Venüs Oğlak",
            "tags": ["ciddi sevgi", "sadakat", "kontrollü kalp"],
            "aura": "Kalbin herkese açık değil; sende sevgi daha seçilmiş ve daha ciddi akar.",
            "trait": "Sen ilişkide güven, sağlamlık ve zamanla derinleşen bağlılık ararsın.",
            "drive": "İçinde gerçek emek görmek, istikrarlı bağ kurmak ve sevgiyi kalıcı bir zemine oturtmak isteği vardır.",
            "shadow": "Bazen fazla kontrollü olabilir ya da duygusal açılmayı geciktirebilirsin.",
        },
        {
            "key": "venus_aquarius",
            "kind": "sign_placement",
            "label_tr": "Venüs Kova",
            "tags": ["sıradışı çekim", "özgürlük", "arkadaşça sevgi"],
            "aura": "Sevgi sende biraz hava ister; yakınlık içinde bile bireyselliğin silinmek istemez.",
            "trait": "Sen ilişkide özgünlük, zihinsel bağ ve alan duygusu ararsın.",
            "drive": "İçinde farklı bir bağ yaşamak, arkadaşlıkla sevginin birleştiği bir ritim kurmak isteği vardır.",
            "shadow": "Bazen duygusal mesafe artabilir ya da istikrar yerine özgürlüğü korumaya odaklanabilirsin.",
        },
        {
            "key": "venus_pisces",
            "kind": "sign_placement",
            "label_tr": "Venüs Balık",
            "tags": ["romantik", "ruhsal sevgi", "ince çekim"],
            "aura": "Sende sevgi bazen gerçeklikten çok rüya gibi hissedilebilir; kalbin ince çalışır.",
            "trait": "Sen ilişkide şefkat, ruh bağı ve çözülmüş yumuşaklık ararsın.",
            "drive": "İçinde ilham verici bir yakınlık, duygusal akış ve kalpten merhamet yaşama isteği vardır.",
            "shadow": "Bazen idealize edebilir, kendini fazla verebilir ya da sınırları kaybedebilirsin.",
        },
    ],
    "mars_signs": [
        {
            "key": "mars_aries",
            "kind": "sign_placement",
            "label_tr": "Mars Koç",
            "tags": ["ham güç", "hızlı aksiyon", "cesaret"],
            "aura": "Bir şey istiyorsan enerjin oraya beklemeden akıyor; sende niyet harekete çok yakın duruyor.",
            "trait": "Sen mücadelede direkt, hızlı ve cesur bir yapı taşırsın.",
            "drive": "İçinde ilk hamleyi yapma, yolu açma ve kendi dürtüne sadık kalma isteği vardır.",
            "shadow": "Bazen fevrilik, sabırsızlık ya da düşünmeden atılma görülebilir.",
        },
        {
            "key": "mars_taurus",
            "kind": "sign_placement",
            "label_tr": "Mars Boğa",
            "tags": ["istikrarlı güç", "inat", "bedensel dayanıklılık"],
            "aura": "Hareketin ani patlamaktan çok, güç toplayıp uzun süre taşıma şeklinde çalışır.",
            "trait": "Sen mücadelede yavaş başlayan ama kolay bırakmayan birisin.",
            "drive": "İçinde sağlam sonuç almak, kendi ritmini korumak ve istikrarlı ilerlemek isteği vardır.",
            "shadow": "Bazen inat sertleşebilir ya da harekete geçmek için fazla bekleyebilirsin.",
        },
        {
            "key": "mars_gemini",
            "kind": "sign_placement",
            "label_tr": "Mars İkizler",
            "tags": ["zihinsel hız", "sözle hareket", "çok yönlü enerji"],
            "aura": "Enerjin tek kanaldan değil; konuşma, fikir ve hareket arasında gidip gelebilir.",
            "trait": "Sen mücadelede zihin, hız ve kelime kullanarak ilerlersin.",
            "drive": "İçinde hareket halinde kalmak, farklı yollar denemek ve enerjiyi canlı tutmak isteği vardır.",
            "shadow": "Bazen dağılabilir, aynı anda çok şeye saldırabilir ya da sözle gereğinden fazla sertleşebilirsin.",
        },
        {
            "key": "mars_cancer",
            "kind": "sign_placement",
            "label_tr": "Mars Yengeç",
            "tags": ["koruyucu güç", "duygusal aksiyon", "içe dönük savunma"],
            "aura": "Enerjin her zaman düz ilerlemeyebilir; duygusal güven arttığında daha güçlü akarsın.",
            "trait": "Sen mücadelede koruyucu, sezgisel ve bazen dolaylı hareket eden bir yapı taşırsın.",
            "drive": "İçinde sevdiklerini korumak, duygusal alanını savunmak ve güvenli zeminde ilerlemek isteği vardır.",
            "shadow": "Bazen pasif-agresif tepki verebilir ya da duygusal dalga yüzünden yön kaybedebilirsin.",
        },
        {
            "key": "mars_leo",
            "kind": "sign_placement",
            "label_tr": "Mars Aslan",
            "tags": ["gururlu güç", "yaratıcı cesaret", "sahne enerjisi"],
            "aura": "Enerjin görünür olmayı sever; sende güç biraz parlak ve iddialı çalışabilir.",
            "trait": "Sen hareket ederken kendinden emin, yaratıcı ve dikkat çeken bir tarz taşırsın.",
            "drive": "İçinde güçlü görünmek, cesur olmak ve yaptığın şeyde iz bırakmak isteği vardır.",
            "shadow": "Bazen gurur savaşı, abartılı tepki ya da egosal çatışma öne çıkabilir.",
        },
        {
            "key": "mars_virgo",
            "kind": "sign_placement",
            "label_tr": "Mars Başak",
            "tags": ["işleyen güç", "detay aksiyonu", "verimli mücadele"],
            "aura": "Enerjin kaba kuvvetten çok, doğru yerden müdahale etme şeklinde çalışır.",
            "trait": "Sen mücadelede dikkatli, pratik ve işlev odaklı bir yapı taşırsın.",
            "drive": "İçinde verimli olmak, sistemi düzeltmek ve gücü boşa harcamamak isteği vardır.",
            "shadow": "Bazen fazla eleştirel olabilir ya da kusur ararken akışı bozabilirsin.",
        },
        {
            "key": "mars_libra",
            "kind": "sign_placement",
            "label_tr": "Mars Terazi",
            "tags": ["ilişkisel mücadele", "denge arayan hareket", "zarif güç"],
            "aura": "Enerjin sert kırmaktan çok, karşılıklı denge kurarak hareket etmeye yatkındır.",
            "trait": "Sen mücadelede ilişkiyi, adaleti ve ölçüyü hesaba katarsın.",
            "drive": "İçinde haklı bir zemin bulmak, estetik ve dengeli biçimde ilerlemek isteği vardır.",
            "shadow": "Bazen kararsız kalabilir ya da doğrudan çatışmaktan kaçınırken pasifleşebilirsin.",
        },
        {
            "key": "mars_scorpio",
            "kind": "sign_placement",
            "label_tr": "Mars Akrep",
            "tags": ["yoğun güç", "strateji", "derin irade"],
            "aura": "Enerjin yüzeyde patlamak zorunda değil; sende güç çoğu zaman içeride birikir.",
            "trait": "Sen mücadelede kararlı, sezgisel ve geri adım atmayan bir yapıya sahipsin.",
            "drive": "İçinde kontrolü kaybetmemek, gücü derin toplamak ve sonuca etkili gitmek isteği vardır.",
            "shadow": "Bazen takıntı, güç savaşı ya da gizli öfke biriktirme görülebilir.",
        },
        {
            "key": "mars_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Mars Yay",
            "tags": ["atak özgürlük", "yüksek enerji", "vizyoner hareket"],
            "aura": "Enerjin dar alanda değil; hareket ettikçe, keşfettikçe ve genişledikçe canlanır.",
            "trait": "Sen mücadelede açık, cesur ve yön duygusuyla ilerleyen birisin.",
            "drive": "İçinde özgür hareket etmek, büyümek ve enerjini daha büyük bir amaca bağlamak isteği vardır.",
            "shadow": "Bazen fazla risk alabilir ya da ayrıntıya sabırsız davranabilirsin.",
        },
        {
            "key": "mars_capricorn",
            "kind": "sign_placement",
            "label_tr": "Mars Oğlak",
            "tags": ["disiplinli güç", "strateji", "yüksek dayanıklılık"],
            "aura": "Enerjin kontrolsüz dağılmaz; sende güç hedefe kilitlenince çok etkili çalışır.",
            "trait": "Sen mücadelede sabırlı, stratejik ve sonuç odaklı bir yapı taşırsın.",
            "drive": "İçinde başarmak, yükselmek ve gücünü somut sonuca çevirmek isteği vardır.",
            "shadow": "Bazen fazla sertleşebilir ya da duyguyu ikinci plana iterek yalnızca sonuca kilitlenebilirsin.",
        },
        {
            "key": "mars_aquarius",
            "kind": "sign_placement",
            "label_tr": "Mars Kova",
            "tags": ["asi enerji", "özgür aksiyon", "farklı yol"],
            "aura": "Enerjin klasik çizgide yürümekten çok, kendi rotasını çizmek ister.",
            "trait": "Sen mücadelede bağımsız, özgün ve kalıpları zorlayan bir yapı taşırsın.",
            "drive": "İçinde özgür olmak, yenilik getirmek ve baskı altında bile kendi çizgini korumak isteği vardır.",
            "shadow": "Bazen ters köşe yapmak uğruna gereğinden fazla kopuk ya da inatçı davranabilirsin.",
        },
        {
            "key": "mars_pisces",
            "kind": "sign_placement",
            "label_tr": "Mars Balık",
            "tags": ["ince güç", "sezgisel hareket", "dalgalı enerji"],
            "aura": "Enerjin her zaman lineer çalışmaz; his doğruysa güçlenir, ruh çekilmiyorsa düşebilir.",
            "trait": "Sen mücadelede sezgi, empati ve içten gelen yön duygusuyla ilerlersin.",
            "drive": "İçinde anlamlı hareket etmek, ruhuna uyan şeye güç vermek ve sert olmayan bir mücadele biçimi kurmak isteği vardır.",
            "shadow": "Bazen yön kaybı, dağılma ya da kararsızlık yüzünden enerjiyi tutmakta zorlanabilirsin.",
        },
    ],
}
