from __future__ import annotations

from typing import Any, Dict, List


PERSONALITY_IMPRINT_LIBRARY_TR_V4: Dict[str, List[Dict[str, Any]]] = {
    "sun_signs": [
        {
            "key": "sun_aries",
            "kind": "sign_placement",
            "label_tr": "Güneş Koç",
            "tags": ["öncü", "cesur", "direkt"],
            "aura": "Sende beklemeyi sevmeyen, canlı ve doğrudan bir yaşam gücü olabilir.",
            "trait": "Sen çoğu zaman hayatla temasını düşünerek değil, deneyerek ve harekete geçerek kurarsın.",
            "drive": "İçinde kendi yolunu açma, ilk adımı atma ve canlı hissetme ihtiyacı güçlüdür.",
            "shadow": "Bazen sabırsızlık, fevrilik ya da hemen sonuç isteme hali öne çıkabilir.",
        },
        {
            "key": "sun_taurus",
            "kind": "sign_placement",
            "label_tr": "Güneş Boğa",
            "tags": ["sağlam", "duyusal", "istikrarlı"],
            "aura": "Sende sakin ama güçlü duran, kolay dağılmayan bir merkez olabilir.",
            "trait": "Sen kimliğini hızla değiştirerek değil, zamanla oturtarak ve sağlamlaştırarak kurarsın.",
            "drive": "İçinde güven, kalıcılık ve gerçekten dokunabildiğin bir hayat kurma isteği vardır.",
            "shadow": "Bazen değişime direnebilir ya da alıştığın zeminden çıkmakta zorlanabilirsin.",
        },
        {
            "key": "sun_gemini",
            "kind": "sign_placement",
            "label_tr": "Güneş İkizler",
            "tags": ["hareketli", "meraklı", "çok yönlü"],
            "aura": "Sende canlı, uyanık ve kolay bağlantı kuran bir yaşam enerjisi olabilir.",
            "trait": "Sen kimliğini tek bir şey üzerinden değil, deneyim, fikir ve iletişim akışı üzerinden kurarsın.",
            "drive": "İçinde öğrenmek, paylaşmak, anlatmak ve zihinsel olarak canlı kalmak isteyen güçlü bir taraf vardır.",
            "shadow": "Bazen dağılabilir, fazla yüzeyde kalabilir ya da kararsızlık yaşayabilirsin.",
        },
        {
            "key": "sun_cancer",
            "kind": "sign_placement",
            "label_tr": "Güneş Yengeç",
            "tags": ["korumacı", "duygusal", "köklü"],
            "aura": "Sende yumuşak ama güçlü, içgüdüsel ve koruyucu bir yaşam enerjisi olabilir.",
            "trait": "Sen kimliğini aidiyet, duygusal bağlar ve iç güven üzerinden kurarsın.",
            "drive": "İçinde ait olmak, korumak ve gerçekten yakın hissettiğin şeylerle köklenmek isteği vardır.",
            "shadow": "Bazen geçmişe fazla bağlanabilir ya da kırılganlığını savunmaya çevirerek içine çekilebilirsin.",
        },
        {
            "key": "sun_leo",
            "kind": "sign_placement",
            "label_tr": "Güneş Aslan",
            "tags": ["görünür", "yaratıcı", "sıcak"],
            "aura": "Sende sıcak, dikkat çeken ve kolay silinmeyen bir merkez olabilir.",
            "trait": "Sen kimliğini görünür olarak, yaratıcı biçimde ve kalpten ifade ederek yaşarsın.",
            "drive": "İçinde parlamak, iz bırakmak ve sevdiğin şeyi canlı biçimde ortaya koymak isteği vardır.",
            "shadow": "Bazen onay ihtiyacı, gurur yarası ya da her şeyin senden dönmesini isteme hali öne çıkabilir.",
        },
        {
            "key": "sun_virgo",
            "kind": "sign_placement",
            "label_tr": "Güneş Başak",
            "tags": ["düzenleyen", "ince bakan", "işlevsel"],
            "aura": "Sende toparlayan, düzenleyen ve detayları fark eden bir merkez olabilir.",
            "trait": "Sen kimliğini fayda, ustalık ve sürekli iyileştirme ihtiyacı üzerinden kurarsın.",
            "drive": "İçinde işe yarar olmak, sistem kurmak ve elindeki şeyi daha iyi hale getirmek isteği vardır.",
            "shadow": "Bazen fazla eleştirel olabilir ya da kendi değerini yeterince kusursuz olmaya bağlayabilirsin.",
        },
        {
            "key": "sun_libra",
            "kind": "sign_placement",
            "label_tr": "Güneş Terazi",
            "tags": ["zarif", "uyumlu", "ilişkisel"],
            "aura": "Sende dengeli, hoş ve insan ilişkileri içinde parlayan bir merkez olabilir.",
            "trait": "Sen kimliğini ilişki kurma, estetik duygusu ve denge yaratma üzerinden yaşarsın.",
            "drive": "İçinde güzellik, karşılıklılık ve zarif bir bağ kurma isteği güçlüdür.",
            "shadow": "Bazen huzuru korumak için kendi merkezini geri plana atabilir ya da kararsız kalabilirsin.",
        },
        {
            "key": "sun_scorpio",
            "kind": "sign_placement",
            "label_tr": "Güneş Akrep",
            "tags": ["yoğun", "güçlü", "derin"],
            "aura": "Sende kolay dağılmayan, derin ve etkisi uzun süren bir merkez olabilir.",
            "trait": "Sen kimliğini yüzeyde kurmaz; gerçeklik, derinlik ve içsel güç üzerinden inşa edersin.",
            "drive": "İçinde kontrolü kaybetmemek, dönüşmek ve hayatı yarım değil tam yaşamak isteği vardır.",
            "shadow": "Bazen kuşku, gizlilik ya da güç savaşlarına açık bir tarafa kayabilirsin.",
        },
        {
            "key": "sun_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Güneş Yay",
            "tags": ["özgür", "vizyoner", "canlı"],
            "aura": "Sende genişleyen, umut veren ve ufku açan bir yaşam enerjisi olabilir.",
            "trait": "Sen kimliğini keşif, anlam ve ileriye dönük hareket üzerinden kurarsın.",
            "drive": "İçinde özgür hissetmek, büyümek ve hayata daha geniş bir yerden bakmak isteyen güçlü bir taraf vardır.",
            "shadow": "Bazen ayrıntıyı ihmal edebilir ya da derin duyguyu hafifleterek geçmeye çalışabilirsin.",
        },
        {
            "key": "sun_capricorn",
            "kind": "sign_placement",
            "label_tr": "Güneş Oğlak",
            "tags": ["ciddi", "sağlam", "hedef odaklı"],
            "aura": "Sende ağırbaşlı, güven veren ve hedefe dönük bir merkez olabilir.",
            "trait": "Sen kimliğini emek, dayanıklılık ve gerçek hayatta bir şey inşa etme üzerinden kurarsın.",
            "drive": "İçinde güçlü olmak, ciddiye alınmak ve kendi değerinle ayakta durmak isteyen güçlü bir taraf vardır.",
            "shadow": "Bazen kendine fazla yüklenebilir ya da duyguyu ikinci plana atarak yalnızca sorumluluğa kilitlenebilirsin.",
        },
        {
            "key": "sun_aquarius",
            "kind": "sign_placement",
            "label_tr": "Güneş Kova",
            "tags": ["özgün", "bağımsız", "gelecekçi"],
            "aura": "Sende farklı duran, özgün ve kendi çizgisini koruyan bir merkez olabilir.",
            "trait": "Sen kimliğini kalıba uyarak değil, kendi bakışını ve zihinsel özgürlüğünü koruyarak yaşarsın.",
            "drive": "İçinde bireysellik, yenilik ve daha farklı bir yol açma isteği vardır.",
            "shadow": "Bazen fazla ayrışabilir, mesafe koyabilir ya da duygusal yakınlık yerine zihinsel üstünlüğe kayabilirsin.",
        },
        {
            "key": "sun_pisces",
            "kind": "sign_placement",
            "label_tr": "Güneş Balık",
            "tags": ["sezgisel", "akışkan", "ruhsal"],
            "aura": "Sende ince hisseden, akışa açık ve kolay tarif edilemeyen bir merkez olabilir.",
            "trait": "Sen kimliğini sadece mantıkla değil, sezgi, his ve ruhsal bağ üzerinden yaşarsın.",
            "drive": "İçinde ilham, şefkat ve görünmeyen katmanlarla temas kurma isteği vardır.",
            "shadow": "Bazen sınır kaybı, belirsizlik ya da kendini fazla dağıtma hali yaşayabilirsin.",
        },
    ],
    "jupiter_signs": [
        {
            "key": "jupiter_aries",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Koç",
            "tags": ["büyüyen cesaret", "öncü şans", "atak genişleme"],
            "aura": "Şansın çoğu zaman hareket ettiğinde açılıyor olabilir.",
            "trait": "Sen büyümeyi cesaret, girişim ve ilk adımı atma üzerinden yaşarsın.",
            "drive": "İçinde risk alarak genişlemek ve kendi gücünü deneyerek artırmak isteği vardır.",
            "shadow": "Bazen fazla acele büyümek isteyebilir ya da sabırsız iyimserlik gösterebilirsin.",
        },
        {
            "key": "jupiter_taurus",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Boğa",
            "tags": ["bereket", "istikrarlı büyüme", "somut şans"],
            "aura": "Sende yavaş ama köklü büyüyen bir bereket duygusu olabilir.",
            "trait": "Sen genişlemeyi sabır, sağlamlık ve somut değer üretme üzerinden yaşarsın.",
            "drive": "İçinde güvenli, verimli ve kalıcı bir hayat kurma isteği vardır.",
            "shadow": "Bazen rahatlığa fazla yaslanabilir ya da büyümeyi yalnızca konforla eşitleyebilirsin.",
        },
        {
            "key": "jupiter_gemini",
            "kind": "sign_placement",
            "label_tr": "Jüpiter İkizler",
            "tags": ["zihinsel genişleme", "iletişim şansı", "çok yönlü büyüme"],
            "aura": "Sende fikirlerle çoğalan, bağlantılarla açılan bir büyüme enerjisi olabilir.",
            "trait": "Sen genişlemeyi öğrenme, anlatma ve zihinsel hareket üzerinden yaşarsın.",
            "drive": "İçinde farklı şeyleri birbirine bağlama ve bilgiyle alan açma isteği vardır.",
            "shadow": "Bazen fazla dağılabilir ya da derinlikten çok çeşitlilikte kalabilirsin.",
        },
        {
            "key": "jupiter_cancer",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Yengeç",
            "tags": ["koruyucu bolluk", "duygusal bereket", "köklü şans"],
            "aura": "Sende besleyen, koruyan ve içten büyüyen bir bereket olabilir.",
            "trait": "Sen büyümeyi aidiyet, duygusal güven ve içten gelen bağlılık üzerinden yaşarsın.",
            "drive": "İçinde hem kendin hem sevdiklerin için güvenli bir alan genişletme isteği vardır.",
            "shadow": "Bazen fazla korumacı olabilir ya da geçmiş bağlarını büyümenin önüne koyabilirsin.",
        },
        {
            "key": "jupiter_leo",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Aslan",
            "tags": ["parlayan şans", "yaratıcı büyüme", "görünür bereket"],
            "aura": "Sende cömert, sıcak ve dikkat çektikçe çoğalan bir büyüme enerjisi olabilir.",
            "trait": "Sen genişlemeyi yaratıcılık, görünürlük ve kendini cesurca ortaya koyma üzerinden yaşarsın.",
            "drive": "İçinde parlamak, etkini büyütmek ve hayatın tadını daha büyük yaşamak isteği vardır.",
            "shadow": "Bazen fazla abartabilir ya da özel olma ihtiyacını büyümenin önüne koyabilirsin.",
        },
        {
            "key": "jupiter_virgo",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Başak",
            "tags": ["işlevsel büyüme", "ustalık", "detaydan bereket"],
            "aura": "Sende düzenledikçe büyüyen, faydayla çoğalan bir bereket olabilir.",
            "trait": "Sen genişlemeyi detay, emek ve sistemli gelişim üzerinden yaşarsın.",
            "drive": "İçinde daha iyi çalışmak, daha iyi yapmak ve fayda yaratarak büyümek isteği vardır.",
            "shadow": "Bazen büyümeyi fazla kontrol etmeye çalışabilir ya da kusur ararken akışı kaçırabilirsin.",
        },
        {
            "key": "jupiter_libra",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Terazi",
            "tags": ["ilişkisel şans", "dengeyle büyüme", "zarif genişleme"],
            "aura": "Sende insanlar, ilişkiler ve uyum üzerinden açılan bir büyüme alanı olabilir.",
            "trait": "Sen genişlemeyi ortaklık, adalet ve güzel bağlantılar kurma üzerinden yaşarsın.",
            "drive": "İçinde zarif bir denge, karşılıklı akış ve ilişki yoluyla çoğalma isteği vardır.",
            "shadow": "Bazen herkesi memnun etmeye çalışabilir ya da kendi yönünü fazla dış dengeye bağlayabilirsin.",
        },
        {
            "key": "jupiter_scorpio",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Akrep",
            "tags": ["derin büyüme", "güçlenen şans", "krizden bereket"],
            "aura": "Sende yüzeyde değil, krizden ve derinlikten büyüyen bir güç olabilir.",
            "trait": "Sen genişlemeyi kontrol, sezgi ve hayatın gizli katmanlarını çözme üzerinden yaşarsın.",
            "drive": "İçinde güçlü olmak, dönüşmek ve derindeki kaynağı bulmak isteği vardır.",
            "shadow": "Bazen gücü büyütürken sertleşebilir ya da kontrol ihtiyacını fazla besleyebilirsin.",
        },
        {
            "key": "jupiter_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Yay",
            "tags": ["doğal genişleme", "yüksek vizyon", "özgür bolluk"],
            "aura": "Sende açık, geniş ve ileriye bakan bir büyüme enerjisi olabilir.",
            "trait": "Sen genişlemeyi keşif, anlam ve ufku genişletme üzerinden yaşarsın.",
            "drive": "İçinde büyümek, özgürleşmek ve daha geniş bir dünya resmi kurmak isteği vardır.",
            "shadow": "Bazen fazla iyimser davranabilir ya da sınırları yeterince hesaba katmayabilirsin.",
        },
        {
            "key": "jupiter_capricorn",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Oğlak",
            "tags": ["stratejik büyüme", "kontrollü genişleme", "başarı bereketi"],
            "aura": "Sende disiplinle çoğalan, yavaş ama sağlam büyüyen bir güç olabilir.",
            "trait": "Sen genişlemeyi plan, emek ve gerçek sonuç alma üzerinden yaşarsın.",
            "drive": "İçinde kalıcı başarı, ciddiye alınan bir yapı ve uzun vadeli güç kurma isteği vardır.",
            "shadow": "Bazen büyümeyi fazla kontrollü tutabilir ya da içten gelen coşkuyu bastırabilirsin.",
        },
        {
            "key": "jupiter_aquarius",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Kova",
            "tags": ["yenilikle büyüme", "kolektif şans", "özgün genişleme"],
            "aura": "Sende farklı olanı büyüten, özgünlükten alan açan bir enerji olabilir.",
            "trait": "Sen genişlemeyi fikir, yenilik ve kolektife dönük vizyon üzerinden yaşarsın.",
            "drive": "İçinde daha farklı bir gelecek, daha açık bir sistem ve zihinsel özgürlük yaratma isteği vardır.",
            "shadow": "Bazen gerçek duygusal bağdan uzaklaşabilir ya da yalnızca fikir düzeyinde kalabilirsin.",
        },
        {
            "key": "jupiter_pisces",
            "kind": "sign_placement",
            "label_tr": "Jüpiter Balık",
            "tags": ["ruhsal bereket", "şefkatle büyüme", "akışkan bolluk"],
            "aura": "Sende sezgiyle çoğalan, akışla büyüyen ve görünmeyen yerlerden açılan bir bereket olabilir.",
            "trait": "Sen genişlemeyi ilham, merhamet ve ruhsal bağlantı üzerinden yaşarsın.",
            "drive": "İçinde daha ince bir anlam, daha büyük bir şefkat ve hayatla akışta buluşma isteği vardır.",
            "shadow": "Bazen sınır kaybı yaşayabilir ya da büyümeyi hayal düzeyinde bırakabilirsin.",
        },
    ],
    "saturn_signs": [
        {
            "key": "saturn_aries",
            "kind": "sign_placement",
            "label_tr": "Satürn Koç",
            "tags": ["kontrollü cesaret", "geciken atılım", "öz disiplin"],
            "aura": "Harekete geçme enerjin çoğu zaman önce testten geçmek ister.",
            "trait": "Sen cesareti doğuştan akıtmak yerine, zamanla inşa etmeye yatkınsın.",
            "drive": "İçinde kontrolsüz değil, sağlam ve gerçek bir güç kurma ihtiyacı vardır.",
            "shadow": "Bazen ilk adımı atmakta zorlanabilir ya da öfkeyi bastırıp biriktirebilirsin.",
        },
        {
            "key": "saturn_taurus",
            "kind": "sign_placement",
            "label_tr": "Satürn Boğa",
            "tags": ["dayanıklılık", "maddi sınav", "sabırlı yapı"],
            "aura": "Sende sağlamlık, dayanıklılık ve kolay sarsılmayan bir yapı olabilir.",
            "trait": "Sen güveni, değeri ve somut dünyayı sabırla kurmak istersin.",
            "drive": "İçinde eksik kalmamak, kendi zeminini güçlendirmek ve istikrar sağlamak isteyen bir taraf vardır.",
            "shadow": "Bazen kıtlık korkusu, tutuculuk ya da aşırı kontrollü güven arayışı öne çıkabilir.",
        },
        {
            "key": "saturn_gemini",
            "kind": "sign_placement",
            "label_tr": "Satürn İkizler",
            "tags": ["ciddi zihin", "ölçülü söz", "iletişim sınavı"],
            "aura": "Zihnin hafif değil; düşündüğün şeyi tartarak, ölçerek ve yapılandırarak ele alır.",
            "trait": "Sen iletişimde kolay açılmayan ama açıldığında sağlam konuşan bir yapı taşırsın.",
            "drive": "İçinde doğru düşünmek, yanlış anlaşılmamak ve zihinsel olarak güçlü görünmek isteği vardır.",
            "shadow": "Bazen kendini sansürleyebilir ya da zihinsel yükü gereğinden fazla büyütebilirsin.",
        },
        {
            "key": "saturn_cancer",
            "kind": "sign_placement",
            "label_tr": "Satürn Yengeç",
            "tags": ["duygusal savunma", "iç güven sınavı", "korunaklı kalp"],
            "aura": "Kalbin kolay açılmayabilir; iç güvenin zamanla ve deneyimle kurulmak ister.",
            "trait": "Sen duygusal alanda ciddi, korumacı ve temkinli bir yapı taşırsın.",
            "drive": "İçinde duygusal olarak güvende olmak, korunmak ve kendi kabuğunu güçlendirmek ihtiyacı vardır.",
            "shadow": "Bazen içine çekilebilir, kırılganlığını saklayabilir ya da duygusal yakınlığı fazla zor bulabilirsin.",
        },
        {
            "key": "saturn_leo",
            "kind": "sign_placement",
            "label_tr": "Satürn Aslan",
            "tags": ["görünürlük sınavı", "yaratıcı blok", "olgun ifade"],
            "aura": "Parlamak isteyen tarafın vardır ama bunu gelişigüzel değil, gerçek hak edişle yapmak istersin.",
            "trait": "Sen görünürlüğü, yaratıcılığı ve kendini ifadeyi zamanla olgunlaştıran birisin.",
            "drive": "İçinde gerçekten özel olmak, gerçekten saygı görmek ve öz değerini kanıtlamak isteği vardır.",
            "shadow": "Bazen görünmekten çekinebilir ya da eleştiri korkusuyla yaratıcı akışı daraltabilirsin.",
        },
        {
            "key": "saturn_virgo",
            "kind": "sign_placement",
            "label_tr": "Satürn Başak",
            "tags": ["ustalık", "disiplin", "detay sorumluluğu"],
            "aura": "Sende işi ciddiye alan, ayrıntıyı boş bırakmayan bir disiplin olabilir.",
            "trait": "Sen düzen, verim ve geliştirme alanında güçlü bir sorumluluk hissi taşırsın.",
            "drive": "İçinde kusursuzu değilse bile sağlamı, temiz olanı ve işleyen sistemi kurmak isteği vardır.",
            "shadow": "Bazen aşırı eleştirel olabilir ya da kendine ve çevrene fazla yük bindirebilirsin.",
        },
        {
            "key": "saturn_libra",
            "kind": "sign_placement",
            "label_tr": "Satürn Terazi",
            "tags": ["ilişkisel ciddiyet", "denge ustalığı", "adalet sorumluluğu"],
            "aura": "Sende ilişkileri hafif değil, ciddi ve dengeli kurmak isteyen bir ton olabilir.",
            "trait": "Sen bağlarda ölçü, karşılıklılık ve gerçek denge ararsın.",
            "drive": "İçinde sağlam bir ilişki zemini, adil bir alışveriş ve zarif bir düzen kurma ihtiyacı vardır.",
            "shadow": "Bazen fazla hesaplı davranabilir ya da duygusal akış yerine formu fazla önemseyebilirsin.",
        },
        {
            "key": "saturn_scorpio",
            "kind": "sign_placement",
            "label_tr": "Satürn Akrep",
            "tags": ["derin savunma", "kontrol", "güç sınavı"],
            "aura": "Sende kolay çözülmeyen, kontrollü ve içeride çok şey tutan bir yoğunluk olabilir.",
            "trait": "Sen güven, güç ve kırılganlık alanlarında ciddi sınavlardan geçerek olgunlaşan birisin.",
            "drive": "İçinde güçsüz kalmamak, kontrolü yitirmemek ve gerçekten güvenli bir derinlik kurmak isteği vardır.",
            "shadow": "Bazen sertleşebilir, kuşkuyu büyütebilir ya da fazla savunmada yaşayabilirsin.",
        },
        {
            "key": "saturn_sagittarius",
            "kind": "sign_placement",
            "label_tr": "Satürn Yay",
            "tags": ["inanç sınavı", "vizyon disiplini", "anlam sorumluluğu"],
            "aura": "Sende büyük resme bakan ama onu gerçeklikle test etmek isteyen bir ciddiyet olabilir.",
            "trait": "Sen inançlarını, fikirlerini ve hayat görüşünü kolay değil, yaşayarak inşa edersin.",
            "drive": "İçinde gerçekten doğru olanı bulmak, anlamı boş slogan değil sağlam zemin yapmak isteği vardır.",
            "shadow": "Bazen fazla katı inanabilir ya da vizyonunu korkuyla daraltabilirsin.",
        },
        {
            "key": "saturn_capricorn",
            "kind": "sign_placement",
            "label_tr": "Satürn Oğlak",
            "tags": ["yüksek sorumluluk", "güçlü yapı", "doğal disiplin"],
            "aura": "Sende ciddi, dayanıklı ve kendi yükünü taşıyabilen bir omurga olabilir.",
            "trait": "Sen sorumluluk, yapı ve uzun vadeli başarı alanında doğuştan güçlü çalışan bir yapıya sahipsin.",
            "drive": "İçinde güçlü kalmak, gerçek sonuç almak ve emek verdiğin şeyin karşılığını görmek isteği vardır.",
            "shadow": "Bazen duyguyu geri plana itebilir ya da kendine insanüstü bir yük bindirebilirsin.",
        },
        {
            "key": "saturn_aquarius",
            "kind": "sign_placement",
            "label_tr": "Satürn Kova",
            "tags": ["zihinsel yapı", "sistem kurma", "sosyal sorumluluk"],
            "aura": "Sende fikirleri ciddiye alan, sistemi dışarıdan değil içeriden kurmak isteyen bir ton olabilir.",
            "trait": "Sen düzeni sırf gelenek diye değil, işe yaradığı için kurmak istersin.",
            "drive": "İçinde özgür ama sağlam, bireysel ama sistemli bir yapı yaratma ihtiyacı vardır.",
            "shadow": "Bazen fazla mesafeli olabilir ya da insan unsurunu ikinci plana itip sistemi aşırı büyütebilirsin.",
        },
        {
            "key": "saturn_pisces",
            "kind": "sign_placement",
            "label_tr": "Satürn Balık",
            "tags": ["ince sınırlar", "ruhsal sorumluluk", "dağılmayı toplama"],
            "aura": "Sende görünmeyen yükleri de hisseden, ince ama ciddi çalışan bir hassasiyet olabilir.",
            "trait": "Sen sezgi, şefkat ve çözülme alanlarını sınır ve sorumlulukla taşımayı öğrenen birisin.",
            "drive": "İçinde dağılmadan hissetmek, akışta kaybolmadan bağ kurmak ve ruhsal olanı zemine indirmek isteği vardır.",
            "shadow": "Bazen yorgunluk, sınır kaybı ya da belirsiz korkularla mücadele edebilirsin.",
        },
    ],
}


ASC_RULER_TONE_LIBRARY_TR_V1: List[Dict[str, Any]] = [
    {
        "key": "asc_ruler_sun",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Güneş",
        "tone_family": ["görünür", "merkezli", "canlı"],
        "tags": ["görünür", "merkezli", "canlı"],
        "aura": "Sende kendini saklamaktan çok, varlığınla alan dolduran bir ton olabilir.",
        "trait": "Hayata girişin görünür, net ve kimlik taşıyan bir yerden olur.",
        "drive": "İçinde kendin olmayı açık yaşama ve etkini görünür kılma isteği vardır.",
        "shadow": "Bazen fazla merkezde kalabilir ya da görünürlüğü güvence gibi kullanabilirsin.",
    },
    {
        "key": "asc_ruler_moon",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Ay",
        "tone_family": ["duygusal", "sezgisel", "korumacı"],
        "tags": ["duygusal", "sezgisel", "korumacı"],
        "aura": "Sende ortamı hemen hisseden ve ona göre şekillenen bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın çoğu zaman içgüdüsel, duygusal ve koruyucu çalışır.",
        "drive": "İçinde duygusal güven, yakınlık ve aitlik kurma ihtiyacı vardır.",
        "shadow": "Bazen ruh haline fazla bağlı hareket edebilir ya da geri çekilerek kendini koruyabilirsin.",
    },
    {
        "key": "asc_ruler_mercury",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Merkür",
        "tone_family": ["uyanık", "zihinsel", "ifadeci"],
        "tags": ["uyanık", "zihinsel", "ifadeci"],
        "aura": "Sende konuşmadan önce bile hissedilen canlı bir zihin tonu olabilir.",
        "trait": "Hayata yaklaşımın gözlem, bağlantı kurma ve anlamlandırma üzerinden çalışır.",
        "drive": "İçinde anlama, anlatma ve hareket halinde düşünme isteği vardır.",
        "shadow": "Bazen fazla zihinselleşebilir ya da her şeyi anlamaya çalışırken yaşamanın ritmini kaçırabilirsin.",
    },
    {
        "key": "asc_ruler_venus",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Venüs",
        "tone_family": ["zarif", "çekici", "uyumlu"],
        "tags": ["zarif", "çekici", "uyumlu"],
        "aura": "Sende yumuşak, hoş ve ilişki kurmayı kolaylaştıran bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın güzellik, uyum ve ilişki akışı üzerinden şekillenebilir.",
        "drive": "İçinde rahat, estetik ve sevilebilir bir alan yaratma ihtiyacı vardır.",
        "shadow": "Bazen huzuru bozmamak için kendi keskin gerçeğini geri plana atabilirsin.",
    },
    {
        "key": "asc_ruler_mars",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Mars",
        "tone_family": ["doğrudan", "atak", "iradeli"],
        "tags": ["doğrudan", "atak", "iradeli"],
        "aura": "Sende beklemeyi sevmeyen, canlı ve güçlü bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın çoğu zaman deneyerek, mücadele ederek ve alan açarak işler.",
        "drive": "İçinde kendi yolunu açmak, doğrudan ilerlemek ve güçlü hissetmek isteği vardır.",
        "shadow": "Bazen fazla sert başlayabilir ya da sabırsızlıkla hız kazanmaya çalışabilirsin.",
    },
    {
        "key": "asc_ruler_jupiter",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Jüpiter",
        "tone_family": ["geniş", "iyimser", "vizyoner"],
        "tags": ["geniş", "iyimser", "vizyoner"],
        "aura": "Sende alan açan, büyüten ve ufuk hissi veren bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın anlam, büyüme ve imkan görme üzerinden çalışır.",
        "drive": "İçinde genişlemek, öğrenmek ve daha büyük bir resme dahil olmak isteği vardır.",
        "shadow": "Bazen sınırları hafife alabilir ya da fazlaca iyimser davranabilirsin.",
    },
    {
        "key": "asc_ruler_saturn",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Satürn",
        "tone_family": ["ciddi", "ölçülü", "yapı kuran"],
        "tags": ["ciddi", "ölçülü", "yapı kuran"],
        "aura": "Sende ağırbaşlı, kontrollü ve güven veren bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın temkin, dayanıklılık ve yapı kurma üzerinden şekillenir.",
        "drive": "İçinde güçlü kalmak, dağılmamak ve kendi düzenini kurmak isteği vardır.",
        "shadow": "Bazen fazla kendini tutabilir ya da hayatı önce sınav sonra akış gibi yaşayabilirsin.",
    },
    {
        "key": "asc_ruler_uranus",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Uranüs",
        "tone_family": ["özgün", "bağımsız", "farklı"],
        "tags": ["özgün", "bağımsız", "farklı"],
        "aura": "Sende klasik çizgiden ayrılan, kolay tarif edilmeyen bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın özgürlük, farklılık ve kendi çizgini koruma üzerinden çalışır.",
        "drive": "İçinde sıradanlıktan uzaklaşmak ve kendi doğrunla yaşamak isteği vardır.",
        "shadow": "Bazen yakınlaşmadan önce kopabilir ya da farklılığı fazla savunmaya çevirebilirsin.",
    },
    {
        "key": "asc_ruler_neptune",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Neptün",
        "tone_family": ["mistik", "akışkan", "sezgisel"],
        "tags": ["mistik", "akışkan", "sezgisel"],
        "aura": "Sende tam çözülemeyen, ince hissedilen ve biraz buğulu bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın sezgi, ilham ve ortamın görünmeyen tarafını hissetme üzerinden çalışır.",
        "drive": "İçinde daha ince bir bağ, daha ruhsal bir akış ve daha derin bir his alanı kurma isteği vardır.",
        "shadow": "Bazen netlik kaybı yaşayabilir ya da sınırlarını fazla geçirgen bırakabilirsin.",
    },
    {
        "key": "asc_ruler_pluto",
        "kind": "asc_ruler_tone",
        "label_tr": "ASC Ruler: Plüto",
        "tone_family": ["yoğun", "manyetik", "güçlü"],
        "tags": ["yoğun", "manyetik", "güçlü"],
        "aura": "Sende hemen açılmayan ama güçlü hissedilen derin bir giriş tonu olabilir.",
        "trait": "Hayata yaklaşımın güç, sezgi ve kontrol kaybını önleme üzerinden şekillenir.",
        "drive": "İçinde etkili olmak, merkezini kaybetmemek ve hayatı derinden kavramak isteği vardır.",
        "shadow": "Bazen fazla savunmada kalabilir ya da yoğunluğu yumuşatmakta zorlanabilirsin.",
    },
]
