from __future__ import annotations


SIGNATURES_V1_TR_EXTRA = [
    {
        "id": "love_7r_in_1_partner_identity",
        "spark": True,
        "block_affinity": ["love_depth", "partner_style"],
        "chips": ["Ayna Etkisi", "Kimlikte Bağ", "Ben–Biz Dengesi"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 1}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "sun_aspect_dsc", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.90},
        "copy_tr": {
            "headline": "İlişki kimliğe dokunur",
            "teaser": "Partner teması sende ‘ben’i çok hızlı görünür kılar; ilişki bir ayna gibi çalışır.",
            "spark": "Birini hayatına aldığında, duruşun ve kararların daha hızlı netleşir; ‘ben’ ile ‘biz’ aynı anda büyür.",
            "gift": "İyi çalıştığında ilişki seni olgunlaştırır ve doğru yönü seçtirir.",
            "watch": "Zorlandığında ‘ben’ alanı daralabilir; küçük sınır cümleleri ilişkiyi daha sağlıklı taşır.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 1}],
    },
    {
        "id": "love_7r_in_2_values_security",
        "spark": True,
        "block_affinity": ["love_depth", "partner_style"],
        "chips": ["Değer", "Güven", "Tutarlılık"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 2}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "venus_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.88},
        "copy_tr": {
            "headline": "Güven = değer uyumu",
            "teaser": "İlişkide en hızlı rahatladığın yer, değerlerin ve düzenin uyumlu olması.",
            "spark": "Sevgi sende sadece his değil; tutarlılık ve ‘aynı zeminde duruyoruz’ hissi.",
            "gift": "İyi çalıştığında uzun vadeli, sakin ve sağlam bağ kurarsın.",
            "watch": "Zorlandığında ‘güven testleri’ artabilir; küçük somut anlaşmalar iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 2}],
    },
    {
        "id": "love_7r_in_3_words_tone",
        "spark": True,
        "block_affinity": ["love_depth"],
        "chips": ["Konuşma Dili", "Ton", "Net Cümle"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 3}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "mercury_aspects_personal", "args": {"max_orb": 4.0}, "add": 0.10}], "cap": 0.90},
        "copy_tr": {
            "headline": "İlişkide söz kası",
            "teaser": "Bağ sende en çok konuşma diliyle büyür; ton bazen her şeydir.",
            "spark": "‘Ne dediğin’ kadar ‘nasıl duyulduğun’ önem kazanır; netlik gelince ilişki rahatlar.",
            "gift": "İyi çalıştığında en zor konuları bile temiz bir dille taşırsın.",
            "watch": "Zorlandığında uzatma ya da sertleşme artabilir; niyet cümlesiyle başlamak dengeyi kurar.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 3}],
    },
    {
        "id": "love_7r_in_4_home_family",
        "spark": True,
        "block_affinity": ["love_depth", "home_roots"],
        "chips": ["Yuva", "Aidiyet", "Kök Güven"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 4}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "moon_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.88},
        "copy_tr": {
            "headline": "Yuva hissi",
            "teaser": "İlişkide seni en çok rahatlatan şey aidiyet ve ‘ev gibi’ his.",
            "spark": "Birlikte ritim kurmak, aynı yerde kök salmak ya da ‘bizim alanımız’ hissi ilişkiyi büyütür.",
            "gift": "İyi çalıştığında çok koruyucu ve sadık bir birliktelik kurarsın.",
            "watch": "Zorlandığında aile dinamikleri ilişkiye sızabilir; sınırları yumuşak ama net tutmak iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 4}],
    },
    {
        "id": "love_7r_in_5_romance_play",
        "spark": True,
        "block_affinity": ["love_depth", "luck_creation"],
        "chips": ["Romantizm", "Oyun", "Neşe"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 5}}],
        "scoring": {"base": 0.45, "boosts": [{"fn": "venus_or_sun_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.86},
        "copy_tr": {
            "headline": "Aşkın neşesi",
            "teaser": "İlişkide ‘keyif’ bir lüks değil; bağın yakıtı.",
            "spark": "Flört, oyun, üretken neşe ve birlikte eğlenmek sende yakınlığı hızlandırır.",
            "gift": "İyi çalıştığında ilişki hem sıcak hem yaratıcı bir yere akar.",
            "watch": "Zorlandığında drama artabilir; neşeyi küçük dozlarda geri çağırmak iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 5}],
    },
    {
        "id": "love_7r_in_6_daily_support",
        "spark": True,
        "block_affinity": ["love_depth"],
        "chips": ["Günlük Destek", "Ritim", "Bakım"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 6}}],
        "scoring": {"base": 0.44, "boosts": [{"fn": "saturn_or_moon_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.85},
        "copy_tr": {
            "headline": "Günlük ritimle büyüyen bağ",
            "teaser": "İlişkide sevgi, günlük destek ve küçük bakımlarla görünür olur.",
            "spark": "Birlikte yaşam ritmi kurulduğunda ilişki güvene oturur; küçük düzenler büyük rahatlık getirir.",
            "gift": "İyi çalıştığında ‘yoldaşlık’ hissi çok güçlenir.",
            "watch": "Zorlandığında eleştiri artabilir; ‘iyileştirme’ dilini seçmek dengeyi kurar.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 6}],
    },
    {
        "id": "love_7r_in_7_equal_partnership",
        "spark": True,
        "block_affinity": ["love_depth"],
        "chips": ["Eşitlik", "Ayna", "Ortaklık"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 7}}],
        "scoring": {"base": 0.44, "boosts": [{"fn": "venus_strong", "args": {"max_orb": 6.0}, "add": 0.08}], "cap": 0.84},
        "copy_tr": {
            "headline": "Eşit ortaklık",
            "teaser": "İlişkide en çok ‘eşitlik ve adalet’ hissi seni açar.",
            "spark": "Net roller, açık anlaşmalar ve karşılıklılık geldiğinde bağ çok hızlı güçlenir.",
            "gift": "İyi çalıştığında ilişkide diplomasi ve denge kurarsın.",
            "watch": "Zorlandığında fazla idare etme görülebilir; kendi ihtiyacını da masaya koymak önemli.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 7}],
    },
    {
        "id": "love_7r_in_8_depth_merge",
        "spark": True,
        "block_affinity": ["love_depth"],
        "chips": ["Güven", "Sadakat", "Derin Temas"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 8}}],
        "scoring": {"base": 0.52, "boosts": [{"fn": "moon_in_house", "args": {"house": 8}, "add": 0.10}], "cap": 0.92},
        "copy_tr": {
            "headline": "Derin bağ",
            "teaser": "Yakınlık sende yüzey değil; güven kurdukça büyür.",
            "spark": "Sevdiğinde yarım sevmezsin; temas gerçekse yaşar, belirsizse yorar.",
            "gift": "İyi çalıştığında çok sadık ve iyileştirici bir bağ kurarsın.",
            "watch": "Zorlandığında eşik tetiklenebilir; küçük netlik cümlesi en iyi köprü.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 8}],
    },
    {
        "id": "love_7r_in_9_distance_learning",
        "spark": True,
        "block_affinity": ["love_depth", "partner_style"],
        "chips": ["Ufuk", "Öğrenme", "Birlikte Büyüme"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 9}}],
        "scoring": {"base": 0.45, "boosts": [{"fn": "jupiter_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.86},
        "copy_tr": {
            "headline": "Birlikte ufuk",
            "teaser": "İlişkide seni büyüten şey ortak vizyon, öğrenme ve ‘beraber genişleme’ hissi.",
            "spark": "Partnerle birlikte yeni bir rota, yeni bir fikir, yeni bir hayat görüşü kurmak sende bağın yakıtı.",
            "gift": "İyi çalıştığında ilişki bir gelişim alanına dönüşür.",
            "watch": "Zorlandığında ‘haklılık’ çatışması artabilir; ortak hedefe dönmek dengeyi kurar.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 9}],
    },
    {
        "id": "love_7r_in_10_public_partner",
        "spark": True,
        "block_affinity": ["love_depth", "career_visibility"],
        "chips": ["Vitrin", "İtibar", "Ortak Hedef"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 10}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "angle_strong", "args": {"angle": "MC"}, "add": 0.08}], "cap": 0.86},
        "copy_tr": {
            "headline": "İlişki görünürlükle birleşir",
            "teaser": "Partner teması sende ‘itibar ve hedef’ hattına bağlanabilir.",
            "spark": "Birlikte hedef koymak, birlikte görünür bir şey inşa etmek bağını güçlendirir.",
            "gift": "İyi çalıştığında ilişki ‘ortak proje’ gibi büyür.",
            "watch": "Zorlandığında beklenti baskısı artabilir; küçük adım ve rol netliği iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 10}],
    },
    {
        "id": "love_7r_in_11_friends_to_love",
        "spark": True,
        "block_affinity": ["love_depth", "partner_style"],
        "chips": ["Arkadaşlıktan Bağ", "Ekip", "Network"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 11}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "dominance_house", "args": {"house": 11, "min_count": 2}, "add": 0.10}], "cap": 0.88},
        "copy_tr": {
            "headline": "Arkadaşlıktan ilişkiye",
            "teaser": "Bağların çoğu sosyal bağlamda büyür; birlikte üretmek güveni hızlandırır.",
            "spark": "İlişki sende çoğu zaman tek kişilik hikâye değil; bir bağlamın içinde derinleşir.",
            "gift": "İyi çalıştığında partnerin aynı zamanda yol arkadaşı olur.",
            "watch": "Zorlandığında rol belirsizliği yorar; küçük netlik zemini kurar.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 11}],
    },
    {
        "id": "love_7r_in_12_private_karmic",
        "spark": True,
        "block_affinity": ["love_depth", "partner_style"],
        "chips": ["Gizli Hassasiyet", "Derin Bağ", "Sessiz Yakınlık"],
        "rules": [{"fn": "house_ruler_in_house", "args": {"house": 7, "target_house": 12}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "neptune_or_venus_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.88},
        "copy_tr": {
            "headline": "Sessiz yakınlık",
            "teaser": "İlişki sende bazen içeride olgunlaşır; duygu önce iç alanda büyür.",
            "spark": "Bazı bağlar sende ‘kadersel’ gibi hissedebilir; temas derin ama dışarıdan sakin görünür.",
            "gift": "İyi çalıştığında çok şefkatli, çok sezgisel bir birliktelik verir.",
            "watch": "Zorlandığında kapanma artabilir; küçük bir sinyal, büyük kopuşu önler.",
        },
        "astro_tokens": [{"type": "ruler_chain", "house": 7, "target_house": 12}],
    },
    {
        "id": "career_mc_ruler_in_1_personal_brand",
        "spark": True,
        "block_affinity": ["career_visibility", "identity_aura"],
        "chips": ["Kişisel Marka", "Sahne", "Duruş"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 1}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "planet_near_angle", "args": {"planet": "Sun", "angle": "ASC", "max_orb": 6.0}, "add": 0.08}], "cap": 0.88},
        "copy_tr": {
            "headline": "Kariyer kimlikle birleşir",
            "teaser": "İşin, duruşun ve görünüşünle çok bağlantılı; ‘sen’ görünür oldukça büyür.",
            "spark": "Bazen tek bir net cümleyle bile yön verirsin; insanlarda güven bırakırsın.",
            "gift": "İyi çalıştığında güçlü bir kişisel marka ve liderlik verir.",
            "watch": "Zorlandığında ‘hazır mıyım’ eşiği artabilir; küçük vitrin adımları ideal.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 1}],
    },
    {
        "id": "career_mc_ruler_in_2_money_value",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Gelir", "Değer", "Somut Sonuç"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 2}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "planet_in_house", "args": {"planet": "Saturn", "house": 2, "add": 0.06}}], "cap": 0.86},
        "copy_tr": {
            "headline": "Değer üreterek büyüme",
            "teaser": "Kariyerin, somut sonuç ve değer üretimiyle güçlenir; ölçülebilir ilerlersin.",
            "spark": "‘Ne işe yarıyor?’ sorusunu iyi cevapladığında fırsatlar açılır.",
            "gift": "İyi çalıştığında istikrarlı gelir ve sağlam bir uzmanlık verir.",
            "watch": "Zorlandığında güveni ‘kontrol’le kurma artabilir; net fiyat/rol anlaşmaları iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 2}],
    },
    {
        "id": "career_mc_ruler_in_3_communication",
        "spark": True,
        "block_affinity": ["career_visibility", "mind_voice"],
        "chips": ["İletişim", "Anlatı", "Net Mesaj"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 3}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "mercury_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.86},
        "copy_tr": {
            "headline": "Sözle etki",
            "teaser": "Kariyerdeki gücün, mesajı doğru kurmak ve insanları aynı cümlede buluşturmak.",
            "spark": "Konuşma, yazma, öğretme, anlatı kurma… bunlar sende doğrudan kariyer kaldıraçı.",
            "gift": "İyi çalıştığında marka dili, ürün dili, strateji ve eğitim alanlarında parlatır.",
            "watch": "Zorlandığında fazla açıklama artabilir; iki maddelik net çerçeve en iyi çözüm.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 3}],
    },
    {
        "id": "career_mc_ruler_in_4_home_base",
        "spark": True,
        "block_affinity": ["career_visibility", "home_roots"],
        "chips": ["Kök", "Zemin", "İç Güven"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 4}}],
        "scoring": {"base": 0.44, "boosts": [{"fn": "moon_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.84},
        "copy_tr": {
            "headline": "Kariyerin zemini ev",
            "teaser": "İş performansın, iç güven ve ev ritmiyle doğrudan bağlantılı.",
            "spark": "İçeride zemin kurunca dışarıda hedefler daha kolay akar.",
            "gift": "İyi çalıştığında sağlam bir ‘base’ üstünden büyürsün; kalıcı ilerlersin.",
            "watch": "Zorlandığında ev–iş dengesi hassaslaşır; ritmi küçük adımlarla korumak önemli.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 4}],
    },
    {
        "id": "career_mc_ruler_in_5_creative_stage",
        "spark": True,
        "block_affinity": ["career_visibility", "luck_creation"],
        "chips": ["Yaratıcılık", "Sahne", "Keyifli Üretim"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 5}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "sun_or_venus_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.86},
        "copy_tr": {
            "headline": "Üreterek görünürlük",
            "teaser": "Kariyerin yaratım ve sahne enerjisiyle büyür; yaptığını göstermek seni yükseltir.",
            "spark": "Senin işin en çok ‘çıktı’ olduğunda konuşur; üretince ışık yanar.",
            "gift": "İyi çalıştığında yaratıcı üretim kariyere dönüşür.",
            "watch": "Zorlandığında mükemmeliyet erteletebilir; ‘yayınlanabilir iyi’ stratejisi ideal.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 5}],
    },
    {
        "id": "career_mc_ruler_in_6_craft_service",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Ustalık", "Rutin", "Zanaat"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 6}}],
        "scoring": {"base": 0.44, "boosts": [{"fn": "saturn_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.84},
        "copy_tr": {
            "headline": "Zanaatla büyüme",
            "teaser": "Kariyerin günlük ustalık ve düzenli ritimle büyür; her gün az ama net ilerlersin.",
            "spark": "Sende kalite, tekrar ve iyileştirme ile oluşur; süreç kurunca hızlanırsın.",
            "gift": "İyi çalıştığında çok güvenilir bir uzmanlığa dönüşür.",
            "watch": "Zorlandığında eleştiri artabilir; ‘iyileştirme’ dilini seçmek iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 6}],
    },
    {
        "id": "career_mc_ruler_in_7_partnership",
        "spark": True,
        "block_affinity": ["career_visibility", "love_depth"],
        "chips": ["Ortaklık", "Müşteri", "İlişki Yönetimi"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 7}}],
        "scoring": {"base": 0.45, "boosts": [{"fn": "venus_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.85},
        "copy_tr": {
            "headline": "Kariyer ortaklıkla büyür",
            "teaser": "İşin, insan ilişkileri ve ortaklıklar üzerinden hız kazanır.",
            "spark": "Doğru kişiyle doğru işi eşleştirdiğinde büyüme çok hızlı olur.",
            "gift": "İyi çalıştığında müşteri, partner, ekip yönetimi güçlü bir kariyer kasına dönüşür.",
            "watch": "Zorlandığında fazla idare etme görülebilir; rol netliği şart.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 7}],
    },
    {
        "id": "career_mc_ruler_in_8_power_finance",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Derinlik", "Strateji", "Güç"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 8}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "pluto_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.86},
        "copy_tr": {
            "headline": "Derin strateji",
            "teaser": "Kariyerde güç, kriz yönetimi ve derin strateji kasın çalışır; zoru yönetirsin.",
            "spark": "Zor konulara girmekten kaçmazsın; doğru çerçeveyle dönüştürürsün.",
            "gift": "İyi çalıştığında yüksek etki ve dönüşüm getirir.",
            "watch": "Zorlandığında kontrol artabilir; güveni ‘şeffaf çerçeve’ ile kurmak iyi gelir.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 8}],
    },
    {
        "id": "career_mc_ruler_in_9_teach_expand",
        "spark": True,
        "block_affinity": ["career_visibility", "talent_gifts"],
        "chips": ["Öğret", "Ufuk", "Yayın"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 9}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "jupiter_strong", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.86},
        "copy_tr": {
            "headline": "Öğreten kariyer",
            "teaser": "Kariyerde ufuk açmak, öğretmek, yayınlamak ya da yol göstermek güçlü çalışır.",
            "spark": "Bilgiyi ‘sisteme’ çevirebildiğinde doğal bir otorite gibi görünürsün.",
            "gift": "İyi çalıştığında mentor/leader etkisi verir.",
            "watch": "Zorlandığında mükemmeliyet erteletebilir; küçük yayın adımları ideal.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 9}],
    },
    {
        "id": "career_mc_ruler_in_10_direct_stage",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Vitrin", "Hedef", "Çıktı"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 10}}],
        "scoring": {"base": 0.50, "boosts": [{"fn": "planet_near_angle", "args": {"planet": "Saturn", "angle": "MC", "max_orb": 6.0}, "add": 0.10}], "cap": 0.90},
        "copy_tr": {
            "headline": "Doğrudan sahne",
            "teaser": "Kariyerin görünürlük ve hedef hattında doğrudan büyür; çıktın konuşur.",
            "spark": "Senin işin ‘tamamlandı’ ve ‘paylaşıldı’ olduğunda hayat hızlanır.",
            "gift": "İyi çalıştığında hızlı yükseliş ve güçlü konum getirir.",
            "watch": "Zorlandığında baskı artabilir; küçük ama düzenli teslimler en iyi denge.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 10}],
    },
    {
        "id": "career_mc_ruler_in_11_network_lift",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Network", "Ekip", "Topluluk"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 11}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "dominance_house", "args": {"house": 11, "min_count": 2}, "add": 0.10}], "cap": 0.88},
        "copy_tr": {
            "headline": "Network kaldıraçı",
            "teaser": "Kariyerin ekip, topluluk ve network ile hızlanır; doğru bağlam büyütür.",
            "spark": "Bir bağlantı, bir işbirliği, bir ekip… sende büyümenin kapısı buradan açılır.",
            "gift": "İyi çalıştığında sosyal kaldıraçla hızlı ölçeklenirsin.",
            "watch": "Zorlandığında rol belirsizliği yorar; görev netliği şart.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 11}],
    },
    {
        "id": "career_mc_ruler_in_12_backstage",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Perde Arkası", "Rafine", "Sessiz Güç"],
        "rules": [{"fn": "angle_ruler_in_house", "args": {"angle": "MC", "target_house": 12}}],
        "scoring": {"base": 0.50, "boosts": [{"fn": "neptune_or_venus_strong", "args": {"max_orb": 6.0}, "add": 0.08}], "cap": 0.90},
        "copy_tr": {
            "headline": "Perde arkası güç",
            "teaser": "En iyi işin içeride olgunlaşınca dışarıda daha güçlü görünür.",
            "spark": "Sen ‘anında vitrin’ değil ‘önce kur, sonra net paket’ yaklaşımıyla büyürsün.",
            "gift": "İyi çalıştığında kalite ve etki aynı yerde birleşir.",
            "watch": "Zorlandığında saklanma artabilir; küçük düzenli vitrin ideal.",
        },
        "astro_tokens": [{"type": "ruler_chain", "angle": "MC", "target_house": 12}],
    },
    {
        "id": "spark_venus_saturn_hard",
        "spark": True,
        "block_affinity": ["love_depth", "mind_voice"],
        "chips": ["Ciddi Sevgi", "Sınır", "Güven İnşası"],
        "rules": [{"fn": "aspect_between", "args": {"a": "Venus", "b": "Saturn", "types": ["Square", "Opposition", "Conjunction"], "max_orb": 6.0}}],
        "scoring": {"base": 0.52, "boosts": [{"fn": "tight_orb_aspect_bonus", "args": {"a": "Venus", "b": "Saturn", "max_orb": 3.0}, "add": 0.12}], "cap": 0.92},
        "copy_tr": {
            "headline": "Sevgiye çerçeve",
            "teaser": "Sevgi sende ciddidir; güven ve tutarlılık olmadan rahat açılmazsın.",
            "spark": "Bağ kurarken standardın yükselir; kalbin ‘gerçek’ ister.",
            "gift": "İyi çalıştığında çok sağlam ve uzun ömürlü bir bağ kurarsın.",
            "watch": "Zorlandığında mesafe artabilir; küçük ama düzenli temas iyi gelir.",
        },
        "astro_tokens": [{"type": "aspect", "a": "Venus", "b": "Saturn"}],
    },
    {
        "id": "spark_moon_saturn_hard",
        "spark": True,
        "block_affinity": ["love_depth", "home_roots"],
        "chips": ["Duygu Disiplini", "Güven", "Korunma"],
        "rules": [{"fn": "aspect_between", "args": {"a": "Moon", "b": "Saturn", "types": ["Square", "Opposition", "Conjunction"], "max_orb": 6.0}}],
        "scoring": {"base": 0.50, "boosts": [{"fn": "moon_in_house", "args": {"house": 8, "add": 0.08}}], "cap": 0.90},
        "copy_tr": {
            "headline": "Duyguda temkin",
            "teaser": "Duyguyu ciddiye alırsın; güven bozulunca kendini korumaya alırsın.",
            "spark": "İçeride ‘güvende miyim?’ sesi güçlü olabilir; tempo düşerse kapanma gelir.",
            "gift": "İyi çalıştığında duygusal dayanıklılık ve sağlam bağ verir.",
            "watch": "Zorlandığında yük artar; duyguyu küçük cümlelerle paylaşmak rahatlatır.",
        },
        "astro_tokens": [{"type": "aspect", "a": "Moon", "b": "Saturn"}],
    },
    {
        "id": "spark_moon_pluto_hard",
        "spark": True,
        "block_affinity": ["love_depth"],
        "chips": ["Derin Duygu", "Dönüşüm", "Gerçek Temas"],
        "rules": [{"fn": "aspect_between", "args": {"a": "Moon", "b": "Pluto", "types": ["Square", "Opposition", "Conjunction"], "max_orb": 6.0}}],
        "scoring": {"base": 0.52, "boosts": [{"fn": "tight_orb_aspect_bonus", "args": {"a": "Moon", "b": "Pluto", "max_orb": 3.0}, "add": 0.12}], "cap": 0.92},
        "copy_tr": {
            "headline": "Duyguda dönüşüm",
            "teaser": "Duygun yüzeyde kalmaz; sevgi sende dönüşüm ister.",
            "spark": "Bazı bağlar sende ‘ya gerçek ya hiç’ gibi çalışabilir.",
            "gift": "İyi çalıştığında çok güçlü bir şifa ve yakınlık kapasitesi verir.",
            "watch": "Zorlandığında kontrol artabilir; şeffaf çerçeve ve sınır iyi gelir.",
        },
        "astro_tokens": [{"type": "aspect", "a": "Moon", "b": "Pluto"}],
    },
    {
        "id": "spark_venus_neptune_hard",
        "spark": True,
        "block_affinity": ["love_depth", "identity_aura"],
        "chips": ["İdeal", "Sis", "Sınır"],
        "rules": [{"fn": "aspect_between", "args": {"a": "Venus", "b": "Neptune", "types": ["Square", "Opposition", "Conjunction"], "max_orb": 6.0}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "tight_orb_aspect_bonus", "args": {"a": "Venus", "b": "Neptune", "max_orb": 3.0}, "add": 0.12}], "cap": 0.90},
        "copy_tr": {
            "headline": "İdeal–gerçek dengesi",
            "teaser": "Sevgide ideal kurarsın; sınır netleşince sis dağılır.",
            "spark": "Bazen ‘olması gereken’ ile ‘olan’ arasındaki fark hassasiyet yaratır.",
            "gift": "İyi çalıştığında romantizm ve sezgisel bağ verir.",
            "watch": "Zorlandığında hayal kırıklığı artabilir; net anlaşmalar iyi gelir.",
        },
        "astro_tokens": [{"type": "aspect", "a": "Venus", "b": "Neptune"}],
    },
    {
        "id": "spark_mercury_neptune_hard",
        "spark": True,
        "block_affinity": ["mind_voice"],
        "chips": ["Sezgi", "Sis", "Net Cümle"],
        "rules": [{"fn": "aspect_between", "args": {"a": "Mercury", "b": "Neptune", "types": ["Square", "Opposition", "Conjunction"], "max_orb": 6.0}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "mercury_angular", "args": {"max_orb": 6.0}, "add": 0.10}], "cap": 0.88},
        "copy_tr": {
            "headline": "Zihinde sis",
            "teaser": "Sezgin güçlü; ama netlik gelmeyince cümle dağılabilir.",
            "spark": "Bazen ‘içeride bildiğin’ şey dışarı çıkarken dağılır; ton hassaslaşır.",
            "gift": "İyi çalıştığında güçlü sezgisel anlatı kurarsın.",
            "watch": "Zorlandığında yanlış anlaşılma artabilir; iki maddelik özet çok işe yarar.",
        },
        "astro_tokens": [{"type": "aspect", "a": "Mercury", "b": "Neptune"}],
    },
    {
        "id": "spark_pluto_angular",
        "spark": True,
        "block_affinity": ["identity_aura", "career_visibility"],
        "chips": ["Ağırlık", "Güç", "Dönüşüm"],
        "rules": [{"fn": "planet_near_angle", "args": {"planet": "Pluto", "angle": "ASC", "max_orb": 5.0}}],
        "scoring": {"base": 0.48, "boosts": [{"fn": "tight_orb_bonus", "args": {"planet": "Pluto", "angle": "ASC", "max_orb": 2.5}, "add": 0.15}], "cap": 0.90},
        "copy_tr": {
            "headline": "Ağır çekim etki",
            "teaser": "Varlığın yoğun; insanlar sende dönüşüm gücü hissedebilir.",
            "spark": "Bir ortamda sessizce bile ‘ağırlık’ bırakırsın; derine inersin.",
            "gift": "İyi çalıştığında kriz yönetimi ve dönüşüm liderliği verir.",
            "watch": "Zorlandığında kontrol artabilir; güveni şeffaf çerçeveyle kurmak iyi gelir.",
        },
        "astro_tokens": [{"type": "angle_hit", "angle": "ASC"}, {"type": "placement", "planet": "Pluto"}],
    },
    {
        "id": "dom_8th_house_emphasis",
        "spark": True,
        "block_affinity": ["love_depth", "home_roots"],
        "chips": ["Derinlik", "Güven", "Eşik"],
        "rules": [{"fn": "dominance_house", "args": {"house": 8, "min_count": 2}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "planet_in_house", "args": {"planet": "Moon", "house": 8, "add": 0.10}}], "cap": 0.88},
        "copy_tr": {
            "headline": "Derin ev teması",
            "teaser": "Hayatın bazı alanlarında ‘yüzey’ değil ‘kök’ istersin; güven eşiğin belirleyicidir.",
            "spark": "Yakınlık artınca içerden içeriye bir ‘eşik’ çalışır; gerçek temas gelince açılırsın.",
            "gift": "İyi çalıştığında güçlü sezgi ve şifa kapasitesi verir.",
            "watch": "Zorlandığında ya hep ya hiç artabilir; küçük sinyaller ilişkiyi taşır.",
        },
        "astro_tokens": [{"type": "house_emphasis", "house": 8}],
    },
    {
        "id": "dom_12th_house_emphasis",
        "spark": True,
        "block_affinity": ["identity_aura", "career_visibility"],
        "chips": ["Perde Arkası", "Sezgi", "Pişirip Çık"],
        "rules": [{"fn": "dominance_house", "args": {"house": 12, "min_count": 2}}],
        "scoring": {"base": 0.45, "boosts": [{"fn": "planet_in_house", "args": {"planet": "Venus", "house": 12, "add": 0.10}}], "cap": 0.86},
        "copy_tr": {
            "headline": "Perde arkası yoğunluk",
            "teaser": "Bazı şeyler sende içeride olgunlaşır; acele değil, ‘pişmiş’ çıkış ister.",
            "spark": "İç dünyan güçlü; sezgiyle çalışırsın ama bunu net paketleyince etkili olursun.",
            "gift": "İyi çalıştığında yaratıcılık ve derin üretim verir.",
            "watch": "Zorlandığında saklanma artabilir; küçük görünürlük adımları dengeyi kurar.",
        },
        "astro_tokens": [{"type": "house_emphasis", "house": 12}],
    },
    {
        "id": "dom_10th_house_emphasis",
        "spark": True,
        "block_affinity": ["career_visibility"],
        "chips": ["Hedef", "Vitrin", "İtibar"],
        "rules": [{"fn": "dominance_house", "args": {"house": 10, "min_count": 2}}],
        "scoring": {"base": 0.46, "boosts": [{"fn": "angle_strong", "args": {"angle": "MC"}, "add": 0.08}], "cap": 0.86},
        "copy_tr": {
            "headline": "Hedef hattı güçlü",
            "teaser": "Toplumdaki rolün, hedef ve itibar çizgisinde belirgin; ‘çıktı’ görünür oldukça büyür.",
            "spark": "Senin işin konuşur; doğru vitrinle etki hızlanır.",
            "gift": "İyi çalıştığında hızlı yükseliş ve güçlü rol verir.",
            "watch": "Zorlandığında baskı artabilir; küçük ama düzenli teslim en iyi strateji.",
        },
        "astro_tokens": [{"type": "house_emphasis", "house": 10}],
    },
]
