from __future__ import annotations

from typing import Any, Dict


SYNSTRY_CATEGORY_TAXONOMY_TR_V1 = [
    "romantic_pull",
    "emotional_safety",
    "friendship_to_love",
    "visible_chemistry",
    "devotional_bond",
    "karmic_pull",
    "commitment_pull",
    "spouse_archetype",
    "partner_recognition",
    "loyalty_pressure",
    "marriage_potential",
    "relationship_weight",
    "shared_future_pull",
    "obsessive_depth",
    "playful_flirt",
    "mental_spark",
    "stability_pull",
    "everyday_bond",
    "care_bond",
    "expansion_bond",
    "admiration_bond",
    "growth_pressure",
    "commitment_weight",
    "healing_bond",
    "freedom_tension",
    "sweetness",
    "friction",
]

SYNSTRY_CATEGORY_DOMAINS: Dict[str, tuple[str, ...]] = {
    "romantic_pull": ("relationships", "intimacy_depth", "creativity_talent"),
    "emotional_safety": ("home_roots", "relationships"),
    "friendship_to_love": ("creativity_talent", "social_future", "relationships"),
    "visible_chemistry": ("creativity_talent", "intimacy_depth", "relationships"),
    "devotional_bond": ("relationships", "home_roots", "identity"),
    "karmic_pull": ("meaning_learning", "relationships", "identity"),
    "commitment_pull": ("relationships", "intimacy_depth", "identity"),
    "spouse_archetype": ("relationships", "home_roots", "social_future"),
    "partner_recognition": ("relationships", "identity", "home_roots"),
    "loyalty_pressure": ("relationships", "home_roots", "private_inner_world"),
    "marriage_potential": ("relationships", "social_future", "home_roots"),
    "relationship_weight": ("relationships", "intimacy_depth", "home_roots"),
    "shared_future_pull": ("social_future", "relationships", "career_visibility"),
    "obsessive_depth": ("intimacy_depth", "private_inner_world", "relationships"),
    "playful_flirt": ("creativity_talent", "relationships", "social_future"),
    "mental_spark": ("mind_communication", "meaning_learning", "relationships"),
    "stability_pull": ("home_roots", "relationships", "identity"),
    "everyday_bond": ("mind_communication", "career_visibility", "relationships"),
    "care_bond": ("home_roots", "private_inner_world", "relationships"),
    "expansion_bond": ("meaning_learning", "social_future", "identity"),
    "admiration_bond": ("career_visibility", "identity", "relationships"),
    "growth_pressure": ("identity", "relationships", "intimacy_depth"),
    "commitment_weight": ("relationships", "home_roots", "identity"),
    "healing_bond": ("private_inner_world", "home_roots", "relationships"),
    "freedom_tension": ("social_future", "identity", "relationships"),
    "sweetness": ("relationships", "home_roots", "creativity_talent"),
    "friction": ("identity", "relationships", "intimacy_depth"),
}

SYNSTRY_CATEGORY_BUNDLE_SUPPORT: Dict[str, tuple[str, ...]] = {
    "romantic_pull": ("soft_attraction_bundle", "8th_personal_cluster", "pluto_personal_bundle"),
    "emotional_safety": ("roots_home_bundle", "soft_attraction_bundle"),
    "friendship_to_love": ("social_future_bundle", "soft_attraction_bundle", "roots_home_bundle"),
    "visible_chemistry": ("soft_attraction_bundle", "8th_personal_cluster", "social_future_bundle"),
    "devotional_bond": ("soft_attraction_bundle", "saturn_angular_bundle", "roots_home_bundle"),
    "karmic_pull": ("nodal_fated_bundle", "identity_activation_bundle", "communication_bridge_bundle"),
    "commitment_pull": ("saturn_angular_bundle", "nodal_fated_bundle", "soft_attraction_bundle"),
    "spouse_archetype": ("saturn_angular_bundle", "nodal_fated_bundle", "roots_home_bundle"),
    "partner_recognition": ("identity_activation_bundle", "soft_attraction_bundle", "roots_home_bundle"),
    "loyalty_pressure": ("saturn_angular_bundle", "12th_pressure_bundle"),
    "marriage_potential": ("saturn_angular_bundle", "soft_attraction_bundle", "nodal_fated_bundle"),
    "relationship_weight": ("saturn_angular_bundle", "8th_personal_cluster", "roots_home_bundle"),
    "shared_future_pull": ("nodal_fated_bundle", "social_future_bundle", "saturn_angular_bundle"),
    "obsessive_depth": ("8th_personal_cluster", "pluto_personal_bundle", "12th_pressure_bundle"),
    "playful_flirt": ("soft_attraction_bundle", "social_future_bundle"),
    "mental_spark": ("communication_bridge_bundle", "nodal_fated_bundle"),
    "stability_pull": ("roots_home_bundle", "saturn_angular_bundle"),
    "everyday_bond": ("communication_bridge_bundle", "roots_home_bundle"),
    "care_bond": ("roots_home_bundle", "12th_pressure_bundle", "soft_attraction_bundle"),
    "expansion_bond": ("nodal_fated_bundle", "social_future_bundle", "identity_activation_bundle"),
    "admiration_bond": ("identity_activation_bundle", "saturn_angular_bundle", "social_future_bundle"),
    "growth_pressure": ("saturn_angular_bundle", "pluto_personal_bundle", "8th_personal_cluster"),
    "commitment_weight": ("saturn_angular_bundle", "roots_home_bundle"),
    "healing_bond": ("12th_pressure_bundle", "roots_home_bundle", "nodal_fated_bundle"),
    "freedom_tension": ("social_future_bundle", "identity_activation_bundle"),
    "sweetness": ("soft_attraction_bundle", "roots_home_bundle"),
    "friction": ("saturn_angular_bundle", "pluto_personal_bundle", "12th_pressure_bundle"),
}

SYNSTRY_CATEGORY_SCORE_CHANNEL: Dict[str, str] = {
    "romantic_pull": "spark",
    "emotional_safety": "bond",
    "friendship_to_love": "bond",
    "visible_chemistry": "spark",
    "devotional_bond": "bond",
    "karmic_pull": "depth",
    "commitment_pull": "bond",
    "spouse_archetype": "bond",
    "partner_recognition": "bond",
    "loyalty_pressure": "risk_index",
    "marriage_potential": "bond",
    "relationship_weight": "depth",
    "shared_future_pull": "bond",
    "obsessive_depth": "depth",
    "playful_flirt": "spark",
    "mental_spark": "bond",
    "stability_pull": "bond",
    "everyday_bond": "bond",
    "care_bond": "bond",
    "expansion_bond": "bond",
    "admiration_bond": "spark",
    "growth_pressure": "risk_index",
    "commitment_weight": "bond",
    "healing_bond": "bond",
    "freedom_tension": "risk_index",
    "sweetness": "bond",
    "friction": "risk_index",
}

SYNSTRY_POSITIVE_CATEGORIES = {
    "romantic_pull",
    "emotional_safety",
    "friendship_to_love",
    "visible_chemistry",
    "devotional_bond",
    "karmic_pull",
    "commitment_pull",
    "spouse_archetype",
    "partner_recognition",
    "marriage_potential",
    "shared_future_pull",
    "playful_flirt",
    "mental_spark",
    "stability_pull",
    "everyday_bond",
    "care_bond",
    "expansion_bond",
    "admiration_bond",
    "healing_bond",
    "sweetness",
}

SYNSTRY_TENSION_CATEGORIES = {
    "obsessive_depth",
    "growth_pressure",
    "commitment_weight",
    "loyalty_pressure",
    "relationship_weight",
    "freedom_tension",
    "friction",
}

_OVERLAY_ENTRY_DEFAULTS = {
    "source_family": "overlay",
    "polarity": "mixed",
}

_ASPECT_ENTRY_DEFAULTS = {
    "source_family": "aspect",
    "polarity": "mixed",
}

_BASE_SYNSTRY_SIGNATURE_LIBRARY_TR_V1 = [
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_7th",
        "kind": "overlay",
        "category": "devotional_bond",
        "label_tr": "A, B'de ilişki hissi açıyor",
        "one_liner": "A'nın varlığı B'ye bu bağın sıradan bir tanışmadan fazlası olabileceğini hissettiriyor.",
        "shadow_line": "Bazen beklenti hızla yükseliyor; bağ daha yaşanmadan zihinde ilişki formuna girebiliyor.",
        "astro_hint_soft": "Güneş + 7.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.64,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_4th",
        "kind": "overlay",
        "category": "emotional_safety",
        "label_tr": "A, B'de ev hissi açıyor",
        "one_liner": "A'nın duygusu B'ye tanıdık, içerden güven veren ve kolay yumuşatan bir his bırakıyor.",
        "shadow_line": "Yakınlık büyüdükçe eski aile duyguları ve korunma ihtiyacı da birlikte uyanabiliyor.",
        "astro_hint_soft": "Ay + 4.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.74,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_5th",
        "kind": "overlay",
        "category": "friendship_to_love",
        "label_tr": "A, B'de sıcak kalp açıyor",
        "one_liner": "A'nın varlığı B'de hem neşeyi hem de daha görünür bir duygusal açıklığı artırıyor.",
        "shadow_line": "Görülme ve karşılık bekleme ihtiyacı büyüdüğünde hassasiyet de artabiliyor.",
        "astro_hint_soft": "Ay + 5.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_7th",
        "kind": "overlay",
        "category": "emotional_safety",
        "label_tr": "A, B'de partnerlik duygusu açıyor",
        "one_liner": "A'nın duygusu B'de yakın ilişki kurma isteğini ve karşılıklı bağ arzusunu güçlendiriyor.",
        "shadow_line": "Duygusal yakınlık arttıkça bağı ilişki tanımına hızlı yerleştirme eğilimi oluşabiliyor.",
        "astro_hint_soft": "Ay + 7.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_8th",
        "kind": "overlay",
        "category": "obsessive_depth",
        "label_tr": "A, B'de derin bağ açıyor",
        "one_liner": "A'nın duygusu B'de yüzeyde kalmayan, mahrem ve kolay unutulmayan bir yakınlık uyandırıyor.",
        "shadow_line": "Bağ güçlendikçe savunmalar, kıskançlık ya da duyguyu fazla sıkı tutma eğilimi yükselebiliyor.",
        "astro_hint_soft": "Ay + 8.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.82,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_5th",
        "kind": "overlay",
        "category": "playful_flirt",
        "label_tr": "A, B'de tatlı flört açıyor",
        "one_liner": "A'nın sevgisi B'de keyfi, romantik canlılığı ve hoş karşılaşma hissini artırıyor.",
        "shadow_line": "Heyecan uzun süre yüksek kaldığında derinliğe geçiş biraz gecikebiliyor.",
        "astro_hint_soft": "Venüs + 5.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_7th",
        "kind": "overlay",
        "category": "devotional_bond",
        "label_tr": "A, B'de ilişki olasılığı açıyor",
        "one_liner": "A'nın sevgisi B'ye bu bağın birlikte yürünebilecek bir ilişkiye dönüşebileceğini hissettiriyor.",
        "shadow_line": "Uyum arzusu bazen gerçek gerilimleri yumuşatıp erteleyebiliyor.",
        "astro_hint_soft": "Venüs + 7.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_8th",
        "kind": "overlay",
        "category": "obsessive_depth",
        "label_tr": "A, B'de yoğun çekim açıyor",
        "one_liner": "A'nın sevgisi B'de tatlı ama yüzeyde kalmayan güçlü bir duygusal ve bedensel çekim yaratıyor.",
        "shadow_line": "Çekim büyüdükçe sahiplenme, duygusal yoğunluk ve kontrol ihtiyacı da artabiliyor.",
        "astro_hint_soft": "Venüs + 8.ev aktivasyonu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.8,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_12th",
        "kind": "overlay",
        "category": "healing_bond",
        "label_tr": "A, B'de gizli kalp açıyor",
        "one_liner": "A'nın sevgisi B'de kolay dile gelmeyen ama içeride derin çalışan bir yumuşama bırakıyor.",
        "shadow_line": "Duygu görünür yaşanmak yerine sessiz, belirsiz ya da içte tutulmuş akabiliyor.",
        "astro_hint_soft": "Venüs + 12.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_5th",
        "kind": "overlay",
        "category": "visible_chemistry",
        "label_tr": "A, B'de canlı çekim açıyor",
        "one_liner": "A'nın enerjisi B'de heyecanı, flörtü ve kalbin hızla ısınmasını artırıyor.",
        "shadow_line": "Ritim fazla yükseldiğinde sabırsızlık ve rekabet de kolay açığa çıkabiliyor.",
        "astro_hint_soft": "Mars + 5.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.74,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_7th",
        "kind": "overlay",
        "category": "growth_pressure",
        "label_tr": "A, B'de güçlü karşılaşma açıyor",
        "one_liner": "A'nın enerjisi B'nin ilişki alanını doğrudan tetikliyor; bu bağ pasif kalmıyor.",
        "shadow_line": "Yakınlık kadar sürtüşme de büyüyebiliyor; çekim ile restleşme aynı hatta çalışabiliyor.",
        "astro_hint_soft": "Mars + 7.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.72,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_8th",
        "kind": "overlay",
        "category": "obsessive_depth",
        "label_tr": "A, B'de yoğun arzu açıyor",
        "one_liner": "A'nın dürtüsü B'de güçlü, derin ve kolay unutulmayan bir yakınlık isteği yaratıyor.",
        "shadow_line": "Güç savaşı, kıskançlık ya da bağı zorlayan bir yoğunluk oluşabiliyor.",
        "astro_hint_soft": "Mars + 8.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.8,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_saturn_in_b_7th",
        "kind": "overlay",
        "category": "commitment_weight",
        "label_tr": "A, B'de ilişkiyi ciddileştiriyor",
        "one_liner": "A'nın varlığı B'de bu bağa daha seçici, daha ciddi ve daha uzun vadeli bakma eğilimi yaratıyor.",
        "shadow_line": "Aynı enerji zaman zaman mesafe, çekingenlik ya da ilişki üstünde ağırlık hissi de getirebiliyor.",
        "astro_hint_soft": "Satürn + 7.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.7,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_pluto_in_b_7th",
        "kind": "overlay",
        "category": "obsessive_depth",
        "label_tr": "A, B'de dönüştürücü ilişki açıyor",
        "one_liner": "A'nın etkisi B'nin partnerlik alanını yoğunlaştırıyor; bu bağ hafif yaşanmıyor.",
        "shadow_line": "Yakınlıkla birlikte kontrol, takıntı ya da güç savaşları da yükselmeye başlayabiliyor.",
        "astro_hint_soft": "Plüton + 7.ev aktivasyonu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.74,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_conj_venus_syn",
        "kind": "aspect",
        "category": "sweetness",
        "label_tr": "Kalp ve sevgi aynı masada",
        "one_liner": "Aranızda yumuşaklık, duygusal sıcaklık ve birbirine kolay ısınan bir bağ var.",
        "shadow_line": "Huzuru koruma isteği bazen zor konuşmaları geciktirebiliyor.",
        "astro_hint_soft": "Ay/Venüs teması",
        "tone_family": "emotional_state",
        "base_score": 0.74,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_trine_venus_syn",
        "kind": "aspect",
        "category": "sweetness",
        "label_tr": "Şefkat akıyor",
        "one_liner": "Aranızdaki sevgi akışı zorlamadan çalışıyor; biri açıldığında diğeri sertleşmeden karşılık verebiliyor.",
        "shadow_line": "Kolaylık bazen ilişkinin zor taraflarını geç fark ettirebiliyor.",
        "astro_hint_soft": "Ay/Venüs akışı",
        "tone_family": "outside_observation",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_conj_mars_syn",
        "kind": "aspect",
        "category": "romantic_pull",
        "label_tr": "Çekim hızlı ateş alıyor",
        "one_liner": "Aranızda sevgiyle arzu aynı hatta çalışıyor; çekim kendini kolay saklamıyor.",
        "shadow_line": "Ritim yükseldiğinde acele, kıskançlık ya da fazla ısınan ilişki dinamiği görülebiliyor.",
        "astro_hint_soft": "Venüs/Mars kavuşumu",
        "tone_family": "direct_trait",
        "base_score": 0.78,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_trine_mars_syn",
        "kind": "aspect",
        "category": "visible_chemistry",
        "label_tr": "Tatlı ve akışkan kimya",
        "one_liner": "Aranızdaki çekim zorlamadan akıyor; sevgiyle istek birbirini sabote etmiyor.",
        "shadow_line": "Bu kolaylık, derinleşme ihtiyacını bazen arka plana atabiliyor.",
        "astro_hint_soft": "Venüs/Mars akışı",
        "tone_family": "mini_scene",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_moon_conj_syn",
        "kind": "aspect",
        "category": "devotional_bond",
        "label_tr": "Birbirinizi doğal hissettiren bağ",
        "one_liner": "Birinizin özü, diğerinizin kalbine tanıdık geliyor; bu da güçlü bir yakınlık duygusu yaratıyor.",
        "shadow_line": "Yakınlık büyüdükçe birbirinden daha fazla duygusal karşılık bekleme oluşabiliyor.",
        "astro_hint_soft": "Güneş/Ay kavuşumu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.78,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_moon_square_syn",
        "kind": "aspect",
        "category": "growth_pressure",
        "label_tr": "Çeken ama zorlayan bağ",
        "one_liner": "Aranızda güçlü bir çekim var ama ihtiyaç ritimleriniz her zaman aynı yerden akmıyor.",
        "shadow_line": "Birinizin doğal akışı diğerini zaman zaman zorlayabiliyor.",
        "astro_hint_soft": "Güneş/Ay karesi",
        "tone_family": "outside_observation",
        "base_score": 0.72,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_moon_trine_syn",
        "kind": "aspect",
        "category": "emotional_safety",
        "label_tr": "Kalpler aynı dili konuşuyor",
        "one_liner": "Duygusal ritimleriniz birbirini yormadan akabiliyor; yakınlık doğal hissediliyor.",
        "shadow_line": "Rahatlık arttığında ilişkinin büyüme isteyen tarafları biraz geri planda kalabiliyor.",
        "astro_hint_soft": "Ay/Ay akışı",
        "tone_family": "emotional_state",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_venus_trine_syn",
        "kind": "aspect",
        "category": "sweetness",
        "label_tr": "Sevgi tarzınız birbirini anlıyor",
        "one_liner": "Birbirinize nasıl sevgi verdiğinizi ve nasıl yakınlaştığınızı doğal olarak anlayabiliyorsunuz.",
        "shadow_line": "Uyum yüksek olduğunda bastırılmış farklılıklar geç görünür hale gelebiliyor.",
        "astro_hint_soft": "Venüs/Venüs akışı",
        "tone_family": "outside_observation",
        "base_score": 0.7,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_square_pluto_syn",
        "kind": "aspect",
        "category": "obsessive_depth",
        "label_tr": "Kalbi derinden tetikleyen bağ",
        "one_liner": "Bu temas duyguları büyütüyor; bağ derinleşirken savunmalar da hızla açılabiliyor.",
        "shadow_line": "Kıskançlık, duygusal kontrol ya da eski yaraların tetiklenmesi görülebiliyor.",
        "astro_hint_soft": "Ay/Plüton sert teması",
        "tone_family": "direct_trait",
        "base_score": 0.78,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_square_uranus_syn",
        "kind": "aspect",
        "category": "freedom_tension",
        "label_tr": "Elektrikli ama dengesiz çekim",
        "one_liner": "Aranızdaki kimya çok canlı; ama ritim her zaman sabit kalmak istemeyebiliyor.",
        "shadow_line": "Bir yakınlaşıp bir uzaklaşan dinamikler oluşabiliyor.",
        "astro_hint_soft": "Venüs/Uranüs sert teması",
        "tone_family": "imagistic_short_line",
        "base_score": 0.76,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_saturn_syn",
        "kind": "aspect",
        "category": "commitment_weight",
        "label_tr": "Sevgiye ağırlık ve ciddiyet geliyor",
        "one_liner": "Aranızdaki bağ yalnızca hoş hissettirmiyor; birlikte durma, emek verme ve ilişkiyi ciddiye alma isteği de yaratıyor.",
        "shadow_line": "Aynı enerji zaman zaman mesafe, çekingenlik ya da sevginin zor akması gibi hissedilebiliyor.",
        "astro_hint_soft": "Venüs/Satürn teması",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "friction",
    },
]

SYNSTRY_SIGNATURE_LIBRARY_TR_WAVE2 = [
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_conj_desc_syn",
        "kind": "angle_contact",
        "category": "devotional_bond",
        "label_tr": "Partner figuru gibi gelen bag",
        "one_liner": "Biriniz digerine yalnizca cekici gelmiyor; onda iliski icin aradigi figuru de gorebiliyor.",
        "shadow_line": "Bag hizla anlam yuklenmis bir iliski hissine donebildigi icin beklenti de ayni hizla yukselebiliyor.",
        "astro_hint_soft": "Gunes + DSC temasi",
        "tone_family": "imagistic_short_line",
        "base_score": 0.78,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_conj_asc_syn",
        "kind": "angle_contact",
        "category": "visible_chemistry",
        "label_tr": "Ilk anda hos gelen cekim",
        "one_liner": "Birinizin sevgisi ve tarzi, digerinin dis dunyada gosterdigi enerjiyle kolayca uyum yakaliyor; cekim gorunur oluyor.",
        "shadow_line": "Ilk hosluk cok guclu oldugunda derindeki farklar biraz gec fark edilebiliyor.",
        "astro_hint_soft": "Venus + ASC temasi",
        "tone_family": "mini_scene",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_conj_desc_syn",
        "kind": "angle_contact",
        "category": "romantic_pull",
        "label_tr": "Tam aranan partner hissi",
        "one_liner": "Biriniz, digerine partner olarak istedigi estetik, yumusaklik ve iliski tonunu cok net hissettirebiliyor.",
        "shadow_line": "Cekim buyudukce ideal partner yansitmasi da artabiliyor.",
        "astro_hint_soft": "Venus + DSC temasi",
        "tone_family": "imagistic_short_line",
        "base_score": 0.8,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_conj_asc_syn",
        "kind": "angle_contact",
        "category": "emotional_safety",
        "label_tr": "Ilk anda duygusal tanisiklik",
        "one_liner": "Birinizin duygusu, digerinin dis dunyada gosterdigi enerjiye hemen temas ediyor; bu da tanidik ve dogal bir yakinlik yaratiyor.",
        "shadow_line": "Hassasiyet de ayni hizla acildigi icin ruh halleri birbirini kolay etkileyebiliyor.",
        "astro_hint_soft": "Ay + ASC temasi",
        "tone_family": "emotional_state",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mars_conj_asc_syn",
        "kind": "angle_contact",
        "category": "visible_chemistry",
        "label_tr": "Bedensel ve canli cekim",
        "one_liner": "Birinizin enerjisi, digerinin varligini dogrudan atesliyor; cekim pasif kalmiyor.",
        "shadow_line": "Ayni temas sabirsizlik, restlesme ya da fiziksel gerilimi de buyutebiliyor.",
        "astro_hint_soft": "Mars + ASC temasi",
        "tone_family": "direct_trait",
        "base_score": 0.78,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "asc_north_node_syn",
        "kind": "node_contact",
        "category": "karmic_pull",
        "label_tr": "Kaderimsi ilk temas",
        "one_liner": "Birinizin varolus bicimi, digerinin yon duygusuna dokunuyor; bag daha ilk anda anlamli hissedilebiliyor.",
        "shadow_line": "Bu kadar guclu tanidiklik hissi bazen bagi oldugundan daha hizli buyutmeye neden olabiliyor.",
        "astro_hint_soft": "ASC + Kuzey Ay Dugumu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.76,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_north_node_syn",
        "kind": "node_contact",
        "category": "growth_pressure",
        "label_tr": "Birbirini yon degistiren bag",
        "one_liner": "Birinizin ozu, digerini kendi yoluna daha ciddi bakmaya ve hayat yonunu gozden gecirmeye itebiliyor.",
        "shadow_line": "Bag yalnizca tatli degil; ayni zamanda buyume baskisi da yaratabiliyor.",
        "astro_hint_soft": "Gunes + Kuzey Ay Dugumu",
        "tone_family": "outside_observation",
        "base_score": 0.74,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_north_node_syn",
        "kind": "node_contact",
        "category": "karmic_pull",
        "label_tr": "Tanidik ama ileri cagiran yakinlik",
        "one_liner": "Birinizin duygusu, digerine hem tanidik hem de donusturucu gelen bir bag kapisi aciyor.",
        "shadow_line": "Bu yakinlik eski duygusal kaliplari da yeniden harekete gecirebiliyor.",
        "astro_hint_soft": "Ay + Kuzey Ay Dugumu",
        "tone_family": "emotional_state",
        "base_score": 0.76,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_north_node_syn",
        "kind": "node_contact",
        "category": "romantic_pull",
        "label_tr": "Tatli ama kaderimsi cekim",
        "one_liner": "Aranizdaki sevgi tonu siradan bir hoslanmadan buyuk gelebiliyor; bagin ozel bir anlami varmis gibi hissedilebiliyor.",
        "shadow_line": "Guzel his cok kuvvetli oldugunda iliskiye oldugundan fazla anlam yuklenebiliyor.",
        "astro_hint_soft": "Venus + Kuzey Ay Dugumu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.78,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mars_north_node_syn",
        "kind": "node_contact",
        "category": "growth_pressure",
        "label_tr": "Harekete geciren kader temasi",
        "one_liner": "Birinizin durtusu ve enerjisi, digerini yerinde birakmiyor; bag yon degistirten bir hareket baslatabiliyor.",
        "shadow_line": "Bu hareket bazen acele, baski ya da gereksiz hiz duygusu yaratabiliyor.",
        "astro_hint_soft": "Mars + Kuzey Ay Dugumu",
        "tone_family": "direct_trait",
        "base_score": 0.74,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mercury_mercury_soft_syn",
        "kind": "aspect",
        "category": "mental_spark",
        "label_tr": "Konusma akiyor",
        "one_liner": "Aranizda konusma dogal akiyor; birbirinizin ne demek istedigini fazla caba harcamadan yakalayabiliyorsunuz.",
        "shadow_line": "Kolay anlasmak bazen bazi farklari konusmadan gecmeye yol acabiliyor.",
        "astro_hint_soft": "Merkur/Merkur akisi",
        "tone_family": "outside_observation",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mercury_mercury_hard_syn",
        "kind": "aspect",
        "category": "friction",
        "label_tr": "Konusma var, surtusme de var",
        "one_liner": "Aranizda zihinsel hareket guclu; ama ayni hiz yanlis anlama, ust uste konusma ve kelime surtusmesi de yaratabiliyor.",
        "shadow_line": "Tartisma bazen konunun kendisinden cok soylenis bicimi ustunden buyuyebiliyor.",
        "astro_hint_soft": "Merkur/Merkur sert temasi",
        "tone_family": "direct_trait",
        "base_score": 0.7,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_mercury_soft_syn",
        "kind": "aspect",
        "category": "mental_spark",
        "label_tr": "Biri digerini gercekten anliyor",
        "one_liner": "Birinizin ozu ile digerinizin zihni arasinda guclu bir kopru var; niyet kolay anlasiliyor.",
        "shadow_line": "Bu rahatlik bazen konusmanin hep ayni rolde akmasina da neden olabiliyor.",
        "astro_hint_soft": "Gunes/Merkur akisi",
        "tone_family": "mini_scene",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mercury_uranus_syn",
        "kind": "aspect",
        "category": "mental_spark",
        "label_tr": "Elektrikli zihin bagi",
        "one_liner": "Konusmalariniz canli, ani ve beklenmedik kivilcimlar tasiyor; birbirinizin zihnini uyandiriyorsunuz.",
        "shadow_line": "Ayni tempo huzursuzluk, kopukluk ya da sabirsiz zihinsel surtusme de yaratabiliyor.",
        "astro_hint_soft": "Merkur/Uranus temasi",
        "tone_family": "imagistic_short_line",
        "base_score": 0.72,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mercury_neptune_soft_syn",
        "kind": "aspect",
        "category": "healing_bond",
        "label_tr": "Ince ve sezgisel konusma",
        "one_liner": "Aranizda yalnizca soylenen degil, hissedilen de dolasiyor; konusma bazen kelimeden fazlasini tasiyor.",
        "shadow_line": "Netlik geri planda kaldiginda ima, belirsizlik ya da yanlis okuma artabiliyor.",
        "astro_hint_soft": "Merkur/Neptun akisi",
        "tone_family": "emotional_state",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mercury_neptune_hard_syn",
        "kind": "aspect",
        "category": "friction",
        "label_tr": "Sisli iletisim",
        "one_liner": "Aranizda guclu bir sezgisel akis olabilir; ama ayni sey yanlis anlama ve bulanik iletisim de yaratabiliyor.",
        "shadow_line": "Bir taraf cok sey soyledigini sanirken diger taraf baska bir sey duyabiliyor.",
        "astro_hint_soft": "Merkur/Neptun sert temasi",
        "tone_family": "direct_trait",
        "base_score": 0.68,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mercury_saturn_syn",
        "kind": "aspect",
        "category": "commitment_weight",
        "label_tr": "Ciddi ve yapi kuran konusma",
        "one_liner": "Aranizda konusma hafif kalmiyor; sorunlari masaya koyup adim adim cozme potansiyeli var.",
        "shadow_line": "Ayni enerji konusmayi kuru, agir ya da elestirel hale de getirebiliyor.",
        "astro_hint_soft": "Merkur/Saturn temasi",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_saturn_syn",
        "kind": "aspect",
        "category": "commitment_weight",
        "label_tr": "Agirligi olan bag",
        "one_liner": "Bu temas iliskiye omurga veriyor; biriniz digerine yalnizca sevgi degil, sorumluluk ve ciddiyet de hissettiriyor.",
        "shadow_line": "Ayni agirlik zaman zaman onay arayisi, baski ya da kendini yeterince rahat gosterememe yaratabiliyor.",
        "astro_hint_soft": "Gunes/Saturn temasi",
        "tone_family": "direct_trait",
        "base_score": 0.72,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_saturn_syn",
        "kind": "aspect",
        "category": "commitment_weight",
        "label_tr": "Kalbi ciddilestiren temas",
        "one_liner": "Aranizdaki duygusal bag hafif degil; yakinlik ayni anda guven ve temkin duygusu yaratabiliyor.",
        "shadow_line": "Bir tarafin ihtiyaclari digerine fazla agir ya da fazla kontrollu gelebiliyor.",
        "astro_hint_soft": "Ay/Saturn temasi",
        "tone_family": "emotional_state",
        "base_score": 0.7,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_saturn_soft_syn",
        "kind": "aspect",
        "category": "commitment_weight",
        "label_tr": "Sevgiye yapi kazandiran bag",
        "one_liner": "Aranizdaki sevgi yalnizca hos hissettirmiyor; kalicilik, sadakat ve emek verme istegi de yaratiyor.",
        "shadow_line": "Iliskiyi fazla kontrollu tutma egilimi sicakligi zaman zaman azaltabiliyor.",
        "astro_hint_soft": "Venus/Saturn akisi",
        "tone_family": "outside_observation",
        "base_score": 0.7,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_saturn_hard_syn",
        "kind": "aspect",
        "category": "friction",
        "label_tr": "Sevgi var, akisi zor",
        "one_liner": "Bagin agirligi yuksek; ama sevgiyle guven ayni hizda akmayinca cekingenlik ve soguma devreye girebiliyor.",
        "shadow_line": "Bir taraf sevgi gosterirken digeri fazla temkinli ya da mesafeli kalabiliyor.",
        "astro_hint_soft": "Venus/Saturn sert temasi",
        "tone_family": "direct_trait",
        "base_score": 0.68,
        "polarity": "friction",
    },
]

SYNSTRY_SIGNATURE_LIBRARY_TR_WAVE3 = [
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_1st",
        "kind": "overlay",
        "category": "visible_chemistry",
        "label_tr": "A, B'de gorunurlugu artiriyor",
        "one_liner": "A'nin varligi B'nin kendini daha gorunur, daha canli ve daha fark edilir hissetmesine yol acabiliyor.",
        "shadow_line": "Ilgi buyudukce ego hassasiyeti ya da fazla kisisellestirme de artabiliyor.",
        "astro_hint_soft": "Gunes + 1.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.7,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_1st",
        "kind": "overlay",
        "category": "emotional_safety",
        "label_tr": "A, B'de duygusal aciklik aciyor",
        "one_liner": "A'nin duygusu B'nin kalbini daha gorunur hale getiriyor; hisler sakli kalmak istemiyor.",
        "shadow_line": "Ruh halleri birbirine kolay gectigi icin hassasiyet de hizla buyuyebiliyor.",
        "astro_hint_soft": "Ay + 1.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_1st",
        "kind": "overlay",
        "category": "visible_chemistry",
        "label_tr": "A, B'yi hos ve cekici buluyor",
        "one_liner": "A'nin sevgisi B'nin tarzina, gorunusune ve varolus bicimine kolayca cekiliyor.",
        "shadow_line": "Ilk begeni cok guclu oldugunda derindeki uyum biraz gec test edilebiliyor.",
        "astro_hint_soft": "Venus + 1.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.74,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_1st",
        "kind": "overlay",
        "category": "visible_chemistry",
        "label_tr": "A, B'yi dogrudan atesliyor",
        "one_liner": "A'nin enerjisi B'nin bedenini, tepkilerini ve kendini ortaya koyma bicimini hizla uyandiriyor.",
        "shadow_line": "Cekim kadar restlesme ve sabirsiz surtusme de buyuyebiliyor.",
        "astro_hint_soft": "Mars + 1.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.76,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_2nd",
        "kind": "overlay",
        "category": "stability_pull",
        "label_tr": "A, B'de deger duygusu aciyor",
        "one_liner": "A'nin varligi B'ye daha saglam durma, kendi degerini hissetme ve birlikte somut zemin kurma istegi verebiliyor.",
        "shadow_line": "Bag, guvence ve sahip olma ihtiyacini gereginden fazla buyutebiliyor.",
        "astro_hint_soft": "Gunes + 2.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_2nd",
        "kind": "overlay",
        "category": "emotional_safety",
        "label_tr": "A, B'de sakin guven aciyor",
        "one_liner": "A'nin duygusu B'ye huzur, sadelik ve duygusal olarak ayakta kalabilecegi bir zemin hissi veriyor.",
        "shadow_line": "Konfor buyudukce degisime direnc de artabiliyor.",
        "astro_hint_soft": "Ay + 2.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.7,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_2nd",
        "kind": "overlay",
        "category": "sweetness",
        "label_tr": "A, B'de degerli his aciyor",
        "one_liner": "A'nin sevgisi B'de sevilme, begenilme ve kendi degerini daha hos bir yerden hissetme duygusu uyandiriyor.",
        "shadow_line": "Sevgi guvenceyle karistiginda birakmak zorlasabiliyor.",
        "astro_hint_soft": "Venus + 2.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.7,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_2nd",
        "kind": "overlay",
        "category": "growth_pressure",
        "label_tr": "A, B'de maddi ve deger alanini zorluyor",
        "one_liner": "A'nin enerjisi B'yi kendi ayaklari ustunde daha guclu durmaya, uretmeye ve somutlasmaya itebiliyor.",
        "shadow_line": "Bu itki zaman zaman sahip olma, para ya da guven alaninda surtusmeye donebiliyor.",
        "astro_hint_soft": "Mars + 2.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_3rd",
        "kind": "overlay",
        "category": "mental_spark",
        "label_tr": "A, B'nin zihnini canlandiriyor",
        "one_liner": "A'nin ozu B'de konusma, paylasma ve gunluk zihinsel akisi daha gorunur hale getiriyor.",
        "shadow_line": "Surekli temas ihtiyaci bazen zihinsel yorgunluk da yaratabiliyor.",
        "astro_hint_soft": "Gunes + 3.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_3rd",
        "kind": "overlay",
        "category": "mental_spark",
        "label_tr": "A, B'yle duygusal konusma aciyor",
        "one_liner": "A'nin duygusu B'nin kelimelerine kolay dokunuyor; konusmalar daha kisisel ve daha samimi hale gelebiliyor.",
        "shadow_line": "Sozler fazla duygusal yuklendiginde kucuk seyler de buyuyebiliyor.",
        "astro_hint_soft": "Ay + 3.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.68,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_3rd",
        "kind": "overlay",
        "category": "friendship_to_love",
        "label_tr": "A, B'yle tatli iletisim aciyor",
        "one_liner": "A'nin sevgisi B'yle konusmayi, mesajlasmayi ve birlikte akmayi dogal olarak keyifli hale getiriyor.",
        "shadow_line": "Kolay iletisim bazen bagin derin tarafini ikinci plana atabiliyor.",
        "astro_hint_soft": "Venus + 3.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_3rd",
        "kind": "overlay",
        "category": "friction",
        "label_tr": "A, B'yle zihinsel hareket ve tartisma aciyor",
        "one_liner": "A'nin enerjisi B'yle konusmalari hizlandiriyor; aranizda kivilcim ve tartisma ayni anda calisabiliyor.",
        "shadow_line": "Uslup sertlestiginde mesele icerikten cok tona kayabiliyor.",
        "astro_hint_soft": "Mars + 3.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.7,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_6th",
        "kind": "overlay",
        "category": "everyday_bond",
        "label_tr": "A, B'nin gunluk duzenine giriyor",
        "one_liner": "A'nin varligi B'nin gunluk hayatinda yer aciyor; bag yalnizca histe degil, rutinde de gorunur hale geliyor.",
        "shadow_line": "Yakinlik isleyise karistiginda elestiri ya da duzen baskisi artabiliyor.",
        "astro_hint_soft": "Gunes + 6.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.66,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_6th",
        "kind": "overlay",
        "category": "care_bond",
        "label_tr": "A, B'de bakim ve destek aciyor",
        "one_liner": "A'nin duygusu B'nin gundelik hayatina sefkat, ilgilenme ve kucuk ama gercek destekler tasiyor.",
        "shadow_line": "Yardim etmek isterken iliski fazla gorev haline gelebiliyor.",
        "astro_hint_soft": "Ay + 6.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_6th",
        "kind": "overlay",
        "category": "care_bond",
        "label_tr": "A, B'yle kucuk seylerde sevgi kuruyor",
        "one_liner": "A'nin sevgisi buyuk jestlerden cok, gundelik hayatin icinde tatli ve ise yarayan bir yakinlik yaratiyor.",
        "shadow_line": "Iliski rahat ama fazla pratik kalirsa romantik sicaklik dusebiliyor.",
        "astro_hint_soft": "Venus + 6.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.66,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_6th",
        "kind": "overlay",
        "category": "growth_pressure",
        "label_tr": "A, B'nin duzenini hizlandiriyor",
        "one_liner": "A'nin enerjisi B'yi harekete geciriyor; birlikteyken isler hizlanabiliyor, tempo artabiliyor.",
        "shadow_line": "Ayni tempo elestiri, sabirsizlik ya da gunluk surtusmeye donebiliyor.",
        "astro_hint_soft": "Mars + 6.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.66,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_9th",
        "kind": "overlay",
        "category": "expansion_bond",
        "label_tr": "A, B'nin ufkunu aciyor",
        "one_liner": "A'nin varligi B'de buyume, kesif ve daha buyuk bir resim gorme istegini canlandiriyor.",
        "shadow_line": "Bag cok hizli idealize edildiginde pratik zemin gec kurulabiliyor.",
        "astro_hint_soft": "Gunes + 9.ev aktivasyonu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_9th",
        "kind": "overlay",
        "category": "expansion_bond",
        "label_tr": "A, B'yle duygusal ufuk aciyor",
        "one_liner": "A'nin duygusu B'ye yalnizca yakinlik degil, genislik ve daha buyuk anlam hissi de tasiyabiliyor.",
        "shadow_line": "Ayni bag bazen duygunun yere basan tarafini hafifletebiliyor.",
        "astro_hint_soft": "Ay + 9.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.68,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_9th",
        "kind": "overlay",
        "category": "friendship_to_love",
        "label_tr": "A, B'yle ilham verici sevgi aciyor",
        "one_liner": "A'nin sevgisi B'yle birlikte ogrenme, gezme, kesfetme ve iliskide ferahlik yasama istegi yaratiyor.",
        "shadow_line": "Ozgunluk hissi buyudukce derinlik ve yerlesme ihtiyaci ertelenebiliyor.",
        "astro_hint_soft": "Venus + 9.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_9th",
        "kind": "overlay",
        "category": "growth_pressure",
        "label_tr": "A, B'yi ileri itiyor",
        "one_liner": "A'nin enerjisi B'yi sinirlarini asmaga, hareket etmeye ve daha cesur yasamaya itebiliyor.",
        "shadow_line": "Ayni itki fikir savasina ya da acele yon degisimine donebiliyor.",
        "astro_hint_soft": "Mars + 9.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.68,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_10th",
        "kind": "overlay",
        "category": "admiration_bond",
        "label_tr": "A, B'de gorunur yonu uyandiriyor",
        "one_liner": "A'nin varligi B'nin hedef, basari ve dis dunyada gorunme alanini guclu bicimde aydinlatiyor.",
        "shadow_line": "Hayranlik buyudukce onay ve beklenti baskisi da artabiliyor.",
        "astro_hint_soft": "Gunes + 10.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.7,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_10th",
        "kind": "overlay",
        "category": "admiration_bond",
        "label_tr": "A, B'nin kamusal alanina duygu tasiyor",
        "one_liner": "A'nin duygusu B'nin gorunur yonunu yalnizca basari degil, hassasiyet ve karsilik ihtiyaciyle de besliyor.",
        "shadow_line": "Dis onayin duygusal agirligi artabiliyor.",
        "astro_hint_soft": "Ay + 10.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.68,
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_10th",
        "kind": "overlay",
        "category": "admiration_bond",
        "label_tr": "A, B'ye hayranlik ve zarif destek veriyor",
        "one_liner": "A'nin sevgisi B'nin gorunur tarafini begeniyor; bu da iliskide takdir ve gurur duygusunu artirabiliyor.",
        "shadow_line": "Bag imaj ustunden fazla beslenirse gercek ihtiyaclar geri planda kalabiliyor.",
        "astro_hint_soft": "Venus + 10.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_10th",
        "kind": "overlay",
        "category": "growth_pressure",
        "label_tr": "A, B'nin hedef alanini zorluyor",
        "one_liner": "A'nin enerjisi B'yi daha cok istemeye, daha yuksege yonelmeye ve gorunur alanda daha guclu durmaya itebiliyor.",
        "shadow_line": "Bu etki destek kadar baski ve rekabet de hissettirebiliyor.",
        "astro_hint_soft": "Mars + 10.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_sun_in_b_11th",
        "kind": "overlay",
        "category": "friendship_to_love",
        "label_tr": "A, B'de arkadaslik ve gelecek hissi aciyor",
        "one_liner": "A'nin varligi B'ye hem dostluk hem de birlikte ileri bakma duygusu verebiliyor.",
        "shadow_line": "Yakinlik uzun sure arkadaslik kabinda kalip derinlesmeyi geciktirebiliyor.",
        "astro_hint_soft": "Gunes + 11.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_moon_in_b_11th",
        "kind": "overlay",
        "category": "friendship_to_love",
        "label_tr": "A, B'de aitlik hissi aciyor",
        "one_liner": "A'nin duygusu B'de sosyal ve duygusal olarak 'ayni taraftayiz' hissini guclendirebiliyor.",
        "shadow_line": "Cevre, grup ya da arkadaslik dinamigi duygunun onune gecebiliyor.",
        "astro_hint_soft": "Ay + 11.ev aktivasyonu",
        "tone_family": "emotional_state",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_venus_in_b_11th",
        "kind": "overlay",
        "category": "sweetness",
        "label_tr": "A, B'yle dost gibi seven bag kuruyor",
        "one_liner": "A'nin sevgisi B'yle rahat, hos ve arkadaslik temelli bir yakinlik yaratiyor.",
        "shadow_line": "Rahatlik artarken romantik gerilim bazen geri planda kalabiliyor.",
        "astro_hint_soft": "Venus + 11.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.68,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_mars_in_b_11th",
        "kind": "overlay",
        "category": "friction",
        "label_tr": "A, B'nin sosyal alanini hareketlendiriyor",
        "one_liner": "A'nin enerjisi B'yle ortak hedefleri ve sosyal akisi hizlandiriyor; birlikteyken hareket artiyor.",
        "shadow_line": "Ayni alan arkadasca rekabet ve grup ici surtusme de yaratabiliyor.",
        "astro_hint_soft": "Mars + 11.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.68,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "sun_vertex_syn",
        "kind": "vertex_contact",
        "category": "karmic_pull",
        "label_tr": "Gorunce tanidik gelen kader temasi",
        "one_liner": "Birinizin ozu, digerinin kader duygusuna cok dogrudan dokunabiliyor; bu bag siradan gelmeyebiliyor.",
        "shadow_line": "Anlamin buyuklugu iliskiye fazla yuk bindirebiliyor.",
        "astro_hint_soft": "Gunes + Vertex",
        "tone_family": "imagistic_short_line",
        "base_score": 0.76,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "moon_vertex_syn",
        "kind": "vertex_contact",
        "category": "karmic_pull",
        "label_tr": "Kalbe kader gibi gelen temas",
        "one_liner": "Birinizin duygusu, digerinde aciklamasi zor ama cok tanidik gelen bir etki birakabiliyor.",
        "shadow_line": "Eski duygusal kaliplar da ayni hizla acilabiliyor.",
        "astro_hint_soft": "Ay + Vertex",
        "tone_family": "emotional_state",
        "base_score": 0.76,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "venus_vertex_syn",
        "kind": "vertex_contact",
        "category": "romantic_pull",
        "label_tr": "Kaderimsi cekim",
        "one_liner": "Aranizdaki hosluk ve cekim normal bir begeniden buyuk hissedilebiliyor; bag ozel bir anlam tasiyor gibi gelebiliyor.",
        "shadow_line": "Cekim fazla buyutuldugunde gercek dengeyi gormek zorlasabiliyor.",
        "astro_hint_soft": "Venus + Vertex",
        "tone_family": "imagistic_short_line",
        "base_score": 0.78,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "mars_vertex_syn",
        "kind": "vertex_contact",
        "category": "growth_pressure",
        "label_tr": "Hizli ve kaderimsi kivilcim",
        "one_liner": "Birinizin durtusu, digerinde ani ve guclu bir karsilik yaratabiliyor; temas beklenenden hizli yogunlasabiliyor.",
        "shadow_line": "Acele, baski ya da fazla yuksek tempo iliskiyi zorlayabiliyor.",
        "astro_hint_soft": "Mars + Vertex",
        "tone_family": "direct_trait",
        "base_score": 0.74,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "asc_vertex_syn",
        "kind": "vertex_contact",
        "category": "karmic_pull",
        "label_tr": "Karsilasmanin anlami buyuyor",
        "one_liner": "Birinizin varolus bicimi, digerinin 'bunu yasamaliyim' duygusuna temas edebiliyor.",
        "shadow_line": "Ilk etkinin buyuklugu bagin gercek hizini gecebiliyor.",
        "astro_hint_soft": "ASC + Vertex",
        "tone_family": "imagistic_short_line",
        "base_score": 0.74,
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "node_vertex_syn",
        "kind": "vertex_contact",
        "category": "karmic_pull",
        "label_tr": "Yol degistirten temas",
        "one_liner": "Bu temas baga yalnizca cekim degil, yon degistirten bir anlam da katabiliyor.",
        "shadow_line": "Buyume baskisi iliskiyi sakin yasamayi zorlastirabiliyor.",
        "astro_hint_soft": "Ay Dugumu + Vertex",
        "tone_family": "outside_observation",
        "base_score": 0.74,
    },
]

SYNSTRY_SIGNATURE_LIBRARY_TR_JUNO_V1 = [
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_juno_in_b_1st",
        "kind": "overlay",
        "category": "partner_recognition",
        "label_tr": "A, B'de partner figuru goruyor",
        "one_liner": "A, B'nin varolus biciminde birlikte yurunebilecek bir eslesme hissi bulabiliyor.",
        "shadow_line": "Ilk tanima duygusu buyudukce iliskiye hizli anlam yuklenebiliyor.",
        "astro_hint_soft": "Juno + 1.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.74,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_juno_in_b_5th",
        "kind": "overlay",
        "category": "devotional_bond",
        "label_tr": "A, B'yle romantik baglilik hissediyor",
        "one_liner": "A, B'yle yalnizca flort degil; kalbi ciddiye alan daha sicak ve ozel bir bag hissedebiliyor.",
        "shadow_line": "Romantik tat buyudukce beklenti de ayni hizla artabiliyor.",
        "astro_hint_soft": "Juno + 5.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.74,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_juno_in_b_7th",
        "kind": "overlay",
        "category": "spouse_archetype",
        "label_tr": "A, B'de es enerjisi goruyor",
        "one_liner": "A, B'yi yalnizca cekici bulmuyor; onda birlikte yurunecek partner figurunu de gorebiliyor.",
        "shadow_line": "Bu kadar guclu partner hissi, bagi oldugundan erken ciddilestirebiliyor.",
        "astro_hint_soft": "Juno + 7.ev aktivasyonu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.8,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_juno_in_b_8th",
        "kind": "overlay",
        "category": "relationship_weight",
        "label_tr": "A, B'yle derin ve baglayici iliski istiyor",
        "one_liner": "A, B'yle yuzeyde kalmayan, sadakat ve mahremiyet tasiyan guclu bir birliktelik hissedebiliyor.",
        "shadow_line": "Bag yogunlastikca sahiplenme ve duygusal agirlik da buyuyebiliyor.",
        "astro_hint_soft": "Juno + 8.ev aktivasyonu",
        "tone_family": "direct_trait",
        "base_score": 0.8,
        "polarity": "friction",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_juno_in_b_10th",
        "kind": "overlay",
        "category": "shared_future_pull",
        "label_tr": "A, B'yle gorunur gelecek dusunuyor",
        "one_liner": "A, B'yle iliskinin yalnizca ozel degil, hayat planina ve gelecege de oturabilecegini hissedebiliyor.",
        "shadow_line": "Birlikte gelecek fikri, iliskinin dogal hizini asabiliyor.",
        "astro_hint_soft": "Juno + 10.ev aktivasyonu",
        "tone_family": "outside_observation",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_OVERLAY_ENTRY_DEFAULTS,
        "key": "a_juno_in_b_11th",
        "kind": "overlay",
        "category": "shared_future_pull",
        "label_tr": "A, B'yle dostluk ustune gelecek kuruyor",
        "one_liner": "A, B'yle hem arkadaslik hem de birlikte uzun yol yurumek potansiyeli gorebiliyor.",
        "shadow_line": "Bag uzun sure dostluk kabinda kalip romantik netligi geciktirebiliyor.",
        "astro_hint_soft": "Juno + 11.ev aktivasyonu",
        "tone_family": "mini_scene",
        "base_score": 0.72,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_conj_sun_syn",
        "kind": "aspect",
        "category": "partner_recognition",
        "label_tr": "Birbirinde es figuru gorme",
        "one_liner": "Birinizin ozu, digerinin iliski ve eslesme beklentisine cok dogrudan temas ediyor.",
        "shadow_line": "Bu temas hizli tanidiklik hissi yarattigi icin beklenti de hizla yukselebiliyor.",
        "astro_hint_soft": "Juno/Gunes kavusumu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_conj_moon_syn",
        "kind": "aspect",
        "category": "devotional_bond",
        "label_tr": "Kalpte baglilik hissi",
        "one_liner": "Birinizin baglilik arzusu, digerinin duygusal dunyasinda guvenli ve ciddi bir yer acabiliyor.",
        "shadow_line": "Yakinlik arttikca duygusal ihtiyac ile iliski beklentisi birbirine fazla karisabiliyor.",
        "astro_hint_soft": "Juno/Ay kavusumu",
        "tone_family": "emotional_state",
        "base_score": 0.76,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_conj_venus_syn",
        "kind": "aspect",
        "category": "marriage_potential",
        "label_tr": "Sevgi ciddilesiyor",
        "one_liner": "Aranizdaki sevgi yalnizca hosluk olarak kalmiyor; birlikte yurunebilir, adanmis bir bag hissi de yaratiyor.",
        "shadow_line": "Iliskiyi guzel his uzerinden fazla idealize etme gorulebiliyor.",
        "astro_hint_soft": "Juno/Venus kavusumu",
        "tone_family": "outside_observation",
        "base_score": 0.78,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_conj_mars_syn",
        "kind": "aspect",
        "category": "commitment_pull",
        "label_tr": "Baglilik ve arzu ayni anda calisiyor",
        "one_liner": "Bu temas yalnizca cekim degil; iliskiyi sahiplenme ve birlikte yurutme durtusu de yaratabiliyor.",
        "shadow_line": "Arzu ve sahiplenme ayni anda buyudugunde kiskanclik ya da baski artabiliyor.",
        "astro_hint_soft": "Juno/Mars kavusumu",
        "tone_family": "direct_trait",
        "base_score": 0.76,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_conj_saturn_syn",
        "kind": "aspect",
        "category": "relationship_weight",
        "label_tr": "Iliskinin omurgasi agirlasiyor",
        "one_liner": "Aranizda bagliligi, sorumlulugu ve uzun vadeyi ciddiye alan guclu bir yapi kurulabiliyor.",
        "shadow_line": "Ayni temas agirlik, cekingenlik ve duygusal mesafe de yaratabiliyor.",
        "astro_hint_soft": "Juno/Saturn kavusumu",
        "tone_family": "outside_observation",
        "base_score": 0.78,
        "polarity": "friction",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_north_node_syn",
        "kind": "aspect",
        "category": "shared_future_pull",
        "label_tr": "Birlikte yol duygusu",
        "one_liner": "Bu temas iliskiyi yalnizca romantik degil, yon degistirten ve gelecege baglanan bir alan haline getirebiliyor.",
        "shadow_line": "Bagin anlami buyudukce dogal akis baski hissine donusebiliyor.",
        "astro_hint_soft": "Juno + Kuzey Ay Dugumu",
        "tone_family": "imagistic_short_line",
        "base_score": 0.78,
        "polarity": "sweet",
    },
    {
        **_ASPECT_ENTRY_DEFAULTS,
        "key": "juno_vertex_syn",
        "kind": "aspect",
        "category": "spouse_archetype",
        "label_tr": "Kaderimsi eslesme hissi",
        "one_liner": "Aranizdaki baglilik temasi siradan gelmiyor; karsilasmanin ozel ve donusturucu bir anlami varmis gibi hissedilebiliyor.",
        "shadow_line": "Bu kadar guclu anlam yuku iliskiyi erken asamada fazla buyutebiliyor.",
        "astro_hint_soft": "Juno + Vertex",
        "tone_family": "imagistic_short_line",
        "base_score": 0.8,
        "polarity": "sweet",
    },
]

SYNSTRY_SIGNATURE_LIBRARY_TR_V1 = [
    *_BASE_SYNSTRY_SIGNATURE_LIBRARY_TR_V1,
    *SYNSTRY_SIGNATURE_LIBRARY_TR_WAVE2,
    *SYNSTRY_SIGNATURE_LIBRARY_TR_WAVE3,
    *SYNSTRY_SIGNATURE_LIBRARY_TR_JUNO_V1,
]

SYNSTRY_SIGNATURE_LIBRARY_INDEX_TR_V1 = {
    str(entry["key"]): dict(entry) for entry in SYNSTRY_SIGNATURE_LIBRARY_TR_V1
}

_ASPECT_LIBRARY_KEY_MAP: Dict[tuple[frozenset[str], str], str] = {
    (frozenset({"moon", "venus"}), "conjunction"): "moon_conj_venus_syn",
    (frozenset({"moon", "venus"}), "trine"): "moon_trine_venus_syn",
    (frozenset({"venus", "mars"}), "conjunction"): "venus_conj_mars_syn",
    (frozenset({"venus", "mars"}), "trine"): "venus_trine_mars_syn",
    (frozenset({"sun", "moon"}), "conjunction"): "sun_moon_conj_syn",
    (frozenset({"sun", "moon"}), "square"): "sun_moon_square_syn",
    (frozenset({"moon", "moon"}), "trine"): "moon_moon_trine_syn",
    (frozenset({"venus", "venus"}), "trine"): "venus_venus_trine_syn",
    (frozenset({"moon", "pluto"}), "square"): "moon_square_pluto_syn",
    (frozenset({"venus", "uranus"}), "square"): "venus_square_uranus_syn",
    (frozenset({"venus", "saturn"}), "*"): "venus_saturn_syn",
}

_BODY_LABELS_TR = {
    "sun": "Güneş",
    "moon": "Ay",
    "mercury": "Merkür",
    "venus": "Venüs",
    "mars": "Mars",
    "jupiter": "Jüpiter",
    "saturn": "Satürn",
    "uranus": "Uranüs",
    "neptune": "Neptün",
    "pluto": "Plüton",
    "juno": "Juno",
    "node": "Ay Düğümü",
    "vertex": "Vertex",
    "asc": "ASC",
    "desc": "DSC",
    "mc": "MC",
}


def body_label_tr(body: Any) -> str:
    key = str(body or "").strip().lower()
    return _BODY_LABELS_TR.get(key, key.replace("_", " ").title())


def overlay_signature_key(body: Any, house: Any) -> str:
    try:
        house_num = int(house)
    except (TypeError, ValueError):
        return ""
    body_key = str(body or "").strip().lower()
    if not body_key or house_num <= 0:
        return ""
    suffix = "th"
    if house_num % 100 not in {11, 12, 13}:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(house_num % 10, "th")
    return f"a_{body_key}_in_b_{house_num}{suffix}"


def aspect_signature_key(a_body: Any, b_body: Any, aspect: Any) -> str:
    pair = frozenset(
        {
            str(a_body or "").strip().lower(),
            str(b_body or "").strip().lower(),
        }
    )
    aspect_key = str(aspect or "").strip().lower()
    if len(pair) != 2 and not pair:
        return ""
    exact = _ASPECT_LIBRARY_KEY_MAP.get((pair, aspect_key))
    if exact:
        return exact
    soft_aspects = {"conjunction", "trine", "sextile"}
    hard_aspects = {"square", "opposition", "quincunx"}
    if pair == frozenset({"sun", "asc"}) and aspect_key == "opposition":
        return "sun_conj_desc_syn"
    if pair == frozenset({"venus", "asc"}) and aspect_key == "conjunction":
        return "venus_conj_asc_syn"
    if pair == frozenset({"venus", "asc"}) and aspect_key == "opposition":
        return "venus_conj_desc_syn"
    if pair == frozenset({"moon", "asc"}) and aspect_key == "conjunction":
        return "moon_conj_asc_syn"
    if pair == frozenset({"mars", "asc"}) and aspect_key == "conjunction":
        return "mars_conj_asc_syn"
    if pair == frozenset({"asc", "node"}) and aspect_key == "conjunction":
        return "asc_north_node_syn"
    if pair == frozenset({"sun", "node"}) and aspect_key == "conjunction":
        return "sun_north_node_syn"
    if pair == frozenset({"moon", "node"}) and aspect_key == "conjunction":
        return "moon_north_node_syn"
    if pair == frozenset({"venus", "node"}) and aspect_key == "conjunction":
        return "venus_north_node_syn"
    if pair == frozenset({"mars", "node"}) and aspect_key == "conjunction":
        return "mars_north_node_syn"
    if pair == frozenset({"mercury", "mercury"}) and aspect_key in soft_aspects:
        return "mercury_mercury_soft_syn"
    if pair == frozenset({"mercury", "mercury"}) and aspect_key in hard_aspects:
        return "mercury_mercury_hard_syn"
    if pair == frozenset({"sun", "mercury"}) and aspect_key in soft_aspects:
        return "sun_mercury_soft_syn"
    if pair == frozenset({"mercury", "uranus"}):
        return "mercury_uranus_syn"
    if pair == frozenset({"mercury", "neptune"}) and aspect_key in soft_aspects:
        return "mercury_neptune_soft_syn"
    if pair == frozenset({"mercury", "neptune"}) and aspect_key in hard_aspects:
        return "mercury_neptune_hard_syn"
    if pair == frozenset({"mercury", "saturn"}):
        return "mercury_saturn_syn"
    if pair == frozenset({"sun", "saturn"}):
        return "sun_saturn_syn"
    if pair == frozenset({"moon", "saturn"}):
        return "moon_saturn_syn"
    if pair == frozenset({"venus", "saturn"}) and aspect_key in soft_aspects:
        return "venus_saturn_soft_syn"
    if pair == frozenset({"venus", "saturn"}) and aspect_key in hard_aspects:
        return "venus_saturn_hard_syn"
    if pair == frozenset({"sun", "vertex"}) and aspect_key == "conjunction":
        return "sun_vertex_syn"
    if pair == frozenset({"moon", "vertex"}) and aspect_key == "conjunction":
        return "moon_vertex_syn"
    if pair == frozenset({"venus", "vertex"}) and aspect_key == "conjunction":
        return "venus_vertex_syn"
    if pair == frozenset({"mars", "vertex"}) and aspect_key == "conjunction":
        return "mars_vertex_syn"
    if pair == frozenset({"asc", "vertex"}) and aspect_key == "conjunction":
        return "asc_vertex_syn"
    if pair == frozenset({"node", "vertex"}) and aspect_key == "conjunction":
        return "node_vertex_syn"
    if pair == frozenset({"juno", "sun"}) and aspect_key == "conjunction":
        return "juno_conj_sun_syn"
    if pair == frozenset({"juno", "moon"}) and aspect_key == "conjunction":
        return "juno_conj_moon_syn"
    if pair == frozenset({"juno", "venus"}) and aspect_key == "conjunction":
        return "juno_conj_venus_syn"
    if pair == frozenset({"juno", "mars"}) and aspect_key == "conjunction":
        return "juno_conj_mars_syn"
    if pair == frozenset({"juno", "saturn"}) and aspect_key == "conjunction":
        return "juno_conj_saturn_syn"
    if pair == frozenset({"juno", "node"}) and aspect_key == "conjunction":
        return "juno_north_node_syn"
    if pair == frozenset({"juno", "vertex"}) and aspect_key == "conjunction":
        return "juno_vertex_syn"
    wildcard = _ASPECT_LIBRARY_KEY_MAP.get((pair, "*"))
    return wildcard or ""
